package com.elog.integration;

import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.test.context.ActiveProfiles;

import java.util.ArrayList;
import java.util.List;
import java.util.stream.Collectors;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * Test-environment cleanup fixture for the HTTP L3 harness.
 *
 * The L3 runner intentionally drives real state-changing APIs. If a run is
 * interrupted, L3QA-* imports can leave today's TripDrafts in PLANNED/VALIDATED
 * state and block the next import through the production delivery-date lock.
 * This fixture removes only namespaced L3QA data generated by the harness.
 */
@SpringBootTest
@ActiveProfiles("dev")
class L3QaDatabaseCleanupFixtureTest {

    @Autowired
    private JdbcTemplate jdbcTemplate;

    @Test
    void removeOnlyReport5L3QaHarnessData() {
        List<Long> batchIds = ids("SELECT id FROM import_batches WHERE file_name LIKE 'L3QA-%'");
        List<Long> orderIds = ids("""
                SELECT o.id
                FROM orders o
                JOIN import_batches b ON b.id = o.import_batch_id
                WHERE b.file_name LIKE 'L3QA-%'
                """);
        List<Long> draftIds = new ArrayList<>(ids("""
                SELECT DISTINCT o.trip_draft_id
                FROM orders o
                JOIN import_batches b ON b.id = o.import_batch_id
                WHERE b.file_name LIKE 'L3QA-%' AND o.trip_draft_id IS NOT NULL
                """));
        draftIds.addAll(ids("""
                SELECT DISTINCT trip_draft_id
                FROM trip_planning_events
                WHERE route_code LIKE 'L3QA-%' AND trip_draft_id IS NOT NULL
                """));
        draftIds = draftIds.stream().distinct().toList();
        List<Long> tripIds = draftIds.isEmpty()
                ? List.of()
                : ids("SELECT trip_id FROM trips WHERE trip_draft_id IN (" + inClause(draftIds) + ")");
        List<Long> executionIds = tripIds.isEmpty()
                ? List.of()
                : ids("SELECT id FROM trip_executions WHERE trip_id IN (" + inClause(tripIds) + ")");
        List<Long> routeIds = ids("SELECT id FROM routes WHERE code LIKE 'L3QA-%'");
        List<Long> storeIds = ids("SELECT id FROM stores WHERE code LIKE 'L3QA-%'");
        List<Long> vehicleIds = ids("SELECT id FROM vehicles WHERE vehicle_code LIKE 'L3QA-%' OR plate_number LIKE 'L3QA-%'");
        List<Long> userIds = ids("SELECT id FROM users WHERE username LIKE 'l3qa_%'");

        jdbcTemplate.execute("SET FOREIGN_KEY_CHECKS = 0");
        try {
            deleteWhereIds("trip_outcome_events", "trip_execution_id", executionIds);
            deleteWhereIds("trip_outcome_events", "trip_id", tripIds);
            deleteWhereIds("trip_outcomes", "trip_execution_id", executionIds);
            deleteWhereIds("delivery_order_results", "trip_execution_id", executionIds);
            deleteWhereIds("delivery_order_results", "order_id", orderIds);
            deleteWhereIds("delivery_exceptions", "trip_execution_id", executionIds);
            deleteWhereIds("delivery_exceptions", "trip_stop_id",
                    tripIds.isEmpty() ? List.of() : ids("SELECT trip_stop_id FROM trip_stops WHERE trip_id IN (" + inClause(tripIds) + ")"));
            deleteWhereIds("delivery_exceptions", "order_id", orderIds);
            deleteWhereIds("trip_executions", "id", executionIds);
            deleteWhereIds("trip_stops", "trip_id", tripIds);
            deleteWhereIds("trips", "trip_id", tripIds);
            deleteWhereIds("manifest_lines", "manifest_id",
                    draftIds.isEmpty() ? List.of() : ids("SELECT manifest_id FROM manifests WHERE trip_draft_id IN (" + inClause(draftIds) + ")"));
            deleteWhereIds("manifests", "trip_draft_id", draftIds);
            deleteWhereIds("trip_planning_events", "trip_draft_id", draftIds);
            deleteWhereIds("trip_planning_events", "trip_id", tripIds);
            deleteWhereIds("trip_draft_stops", "trip_draft_id", draftIds);
            deleteWhereIds("trip_drafts", "id", draftIds);
            deleteWhereIds("order_items", "order_id", orderIds);
            deleteWhereIds("orders", "id", orderIds);
            deleteWhereIds("import_errors", "import_batch_id", batchIds);
            deleteWhereIds("import_batches", "id", batchIds);
            deleteWhereIds("route_stops", "route_id", routeIds);
            deleteWhereIds("route_stops", "store_id", storeIds);
            deleteWhereIds("routes", "id", routeIds);
            deleteWhereIds("stores", "id", storeIds);
            deleteWhereIds("vehicles", "id", vehicleIds);
            deleteWhereIds("user_roles", "user_id", userIds);
            deleteWhereIds("users", "id", userIds);
        } finally {
            jdbcTemplate.execute("SET FOREIGN_KEY_CHECKS = 1");
        }

        Integer remainingBatches = jdbcTemplate.queryForObject(
                "SELECT COUNT(*) FROM import_batches WHERE file_name LIKE 'L3QA-%'", Integer.class);
        assertThat(remainingBatches).isZero();
    }

    private List<Long> ids(String sql) {
        return jdbcTemplate.queryForList(sql, Long.class);
    }

    private String inClause(List<Long> ids) {
        return ids.stream().map(String::valueOf).collect(Collectors.joining(","));
    }

    private void deleteWhereIds(String table, String column, List<Long> ids) {
        if (!ids.isEmpty()) {
            jdbcTemplate.update("DELETE FROM " + table + " WHERE " + column + " IN (" + inClause(ids) + ")");
        }
    }
}
