package com.elog.integration;

import com.elog.dto.response.trip.PlanningEventResponse;
import com.elog.entity.PlanningActorType;
import com.elog.entity.PlanningEventType;
import com.elog.entity.TripPlanningEvent;
import com.elog.repository.TripPlanningEventRepository;
import com.elog.service.PlanningHistoryService;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.ActiveProfiles;
import org.springframework.transaction.annotation.Transactional;

import java.time.LocalDate;
import java.util.List;

import static org.assertj.core.api.Assertions.assertThat;

@SpringBootTest
@ActiveProfiles("dev")
@Transactional
@ExtendWith(Report5L2EvidenceExtension.class)
class PlanningHistoryServiceIntegrationTest {

    @Autowired
    private PlanningHistoryService planningHistoryService;

    @Autowired
    private TripPlanningEventRepository tripPlanningEventRepository;

    @Test
    void l2Plh01RecordsAndPersistsPlanningEventInDatabase() {
        PlanningHistoryService.PlanningEventInput input = new PlanningHistoryService.PlanningEventInput(
                100L,
                null,
                PlanningEventType.TRIP_DRAFT_CREATED,
                PlanningActorType.SYSTEM,
                "system",
                null,
                "DRAFT",
                "Trip draft auto-generated by batch scheduler",
                null,
                null,
                null,
                null,
                "RT-001",
                LocalDate.now()
        );

        planningHistoryService.record(input);

        List<TripPlanningEvent> events = tripPlanningEventRepository.findAll();
        assertThat(events).isNotEmpty();
        TripPlanningEvent saved = events.stream()
                .filter(e -> Long.valueOf(100L).equals(e.getTripDraftId()))
                .findFirst()
                .orElseThrow();
        assertThat(saved.getEventType()).isEqualTo(PlanningEventType.TRIP_DRAFT_CREATED);
        assertThat(saved.getStatusAfter()).isEqualTo("DRAFT");
    }

    @Test
    void l2Plh02QueriesHistoryEventsWithFilter() {
        PlanningHistoryService.PlanningHistoryFilter filter = new PlanningHistoryService.PlanningHistoryFilter(
                null, null, null, null, null, null, null, null, null
        );

        com.elog.dto.response.common.ApiResponse<List<PlanningEventResponse>> res =
                planningHistoryService.search(filter, PageRequest.of(0, 10));
        assertThat(res).isNotNull();
        assertThat(res.getData()).isNotNull();
    }
}
