package com.elog.service;

import com.elog.dto.response.*;
import com.elog.entity.*;
import com.elog.exception.BusinessException;
import com.elog.exception.ErrorCode;
import com.elog.repository.*;
import com.elog.service.impl.*;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import java.math.BigDecimal;import java.time.*;import java.util.*;
import static org.junit.jupiter.api.Assertions.*;import static org.mockito.Mockito.*;

@ExtendWith(MockitoExtension.class)
class RecommendationServiceImplReport5Test{
 @Mock TripDraftRepository drafts;@Mock TripDraftStopRepository stops;@Mock VehicleRepository vehicles;@Mock TripRepository trips;@Mock UserRepository users;@Mock OrderRepository orders;@Mock SystemConfigRepository configs;@Mock TripExecutionRepository executions;@Mock PlanningHistoryService history;
 RecommendationServiceImpl service;TripDraft draft;Store store;TripDraftStop stop;
 @BeforeEach void setup(){service=new RecommendationServiceImpl(drafts,stops,vehicles,trips,users,orders,configs,new ConstraintValidationServiceImpl(),executions,history);store=Store.builder().id(1L).code("S1").allowedDeliveryHours("All").build();draft=TripDraft.builder().id(1L).status("PLANNED").deliveryDate(LocalDate.of(2026,8,14)).totalVolumeM3(new BigDecimal("5")).totalWeightKg(new BigDecimal("1000")).build();stop=TripDraftStop.builder().id(1L).store(store).sequenceNo(1).isActive(true).plannedEta(LocalDateTime.of(2026,8,14,9,0)).build();}
 User driver(long id){return User.builder().id(id).username("d"+id).fullName("Driver "+id).isActive(true).driverStatus(DriverStatus.ACTIVE).roles(Set.of(Role.builder().name("DRIVER").build())).build();}
 Vehicle vehicle(long id,String volume,String weight,String cost){return Vehicle.builder().id(id).plateNumber("P"+id).vehicleType("VAN").status(VehicleStatus.AVAILABLE).isActive(true).maxVolumeM3(new BigDecimal(volume)).payloadKg(new BigDecimal(weight)).costPerKm(new BigDecimal(cost)).assignedDriver(driver(100+id)).build();}
 RecommendationResultResponse single(List<Vehicle> fleet){when(drafts.findById(1L)).thenReturn(Optional.of(draft));when(stops.findByTripDraftIdAndIsActiveTrueOrderBySequenceNoAsc(1L)).thenReturn(List.of(stop));when(vehicles.findByIsActiveTrue()).thenReturn(fleet);when(orders.findByTripDraftId(1L)).thenReturn(List.of());return service.recommendTop3(1L);}
 @Test @DisplayName("[L1-RC-01] one feasible vehicle ranks first with seventy-thirty score") void oneVehicleScores(){RecommendationResultResponse r=single(List.of(vehicle(1,"10","2000","10")));assertAll(()->assertEquals("SINGLE_VEHICLE",r.getPlanType()),()->assertEquals(1,r.getRecommendations().size()),()->assertEquals(new BigDecimal("35.00"),r.getRecommendations().getFirst().getTotalScore()));}
 @Test @DisplayName("[L1-RC-02] three feasible vehicles are ranked by total score descending") void threeVehiclesRankDescending(){RecommendationResultResponse r=single(List.of(vehicle(1,"20","4000","10"),vehicle(2,"10","2000","10"),vehicle(3,"8","1600","10")));List<BigDecimal>s=r.getRecommendations().stream().map(VehicleRecommendationResponse::getTotalScore).toList();assertAll(()->assertEquals(3,s.size()),()->assertTrue(s.get(0).compareTo(s.get(1))>=0),()->assertTrue(s.get(1).compareTo(s.get(2))>=0));}
 @Test @DisplayName("[L1-RC-03] five feasible vehicles are capped at top three") void fiveVehiclesAreCapped(){RecommendationResultResponse r=single(List.of(vehicle(1,"20","4000","10"),vehicle(2,"18","3600","10"),vehicle(3,"16","3200","10"),vehicle(4,"14","2800","10"),vehicle(5,"12","2400","10")));assertEquals(3,r.getRecommendations().size());}
 @Test @DisplayName("[L1-RC-04] capacity score averages volume and weight fill") void capacityAveragesBothFills(){draft.setTotalVolumeM3(new BigDecimal("5"));draft.setTotalWeightKg(new BigDecimal("500"));RecommendationResultResponse r=single(List.of(vehicle(1,"10","2000","10")));assertEquals(new BigDecimal("26.25"),r.getRecommendations().getFirst().getTotalScore());}
 @Test @DisplayName("[L1-RC-05] lower cost per kilometre receives higher normalized cost score") void lowerCostScoresHigher(){Vehicle cheap=vehicle(1,"10","2000","5"),expensive=vehicle(2,"10","2000","10");RecommendationResultResponse r=single(List.of(expensive,cheap));assertAll(()->assertEquals(1L,r.getRecommendations().getFirst().getVehicles().getFirst().getVehicleId()),()->assertTrue(r.getRecommendations().get(0).getTotalScore().compareTo(r.getRecommendations().get(1).getTotalScore())>0));}
 @Test @DisplayName("[L1-RC-07] no vehicle passing hard constraints returns NO_PLAN") void noFeasibleVehicleReturnsNoPlan(){RecommendationResultResponse r=single(List.of(vehicle(1,"1","100","10")));assertAll(()->assertEquals("NO_PLAN",r.getPlanType()),()->assertTrue(r.getRecommendations().isEmpty()),()->assertFalse(r.getViolatedConstraints().isEmpty()));}
 @Test @DisplayName("[L1-RC-08] missing trip draft returns TRIP_DRAFT_NOT_FOUND") void missingDraftIsRejected(){when(drafts.findById(999L)).thenReturn(Optional.empty());BusinessException e=assertThrows(BusinessException.class,()->service.recommendTop3(999L));assertEquals(ErrorCode.TRIP_DRAFT_NOT_FOUND,e.getErrorCode());}
 @Test @DisplayName("[L1-RC-09] draft without active stops returns empty NO_PLAN") void noStopsReturnsNoPlan(){when(drafts.findById(1L)).thenReturn(Optional.of(draft));when(stops.findByTripDraftIdAndIsActiveTrueOrderBySequenceNoAsc(1L)).thenReturn(List.of());RecommendationResultResponse r=service.recommendTop3(1L);assertAll(()->assertEquals("NO_PLAN",r.getPlanType()),()->assertTrue(r.getRecommendations().isEmpty()));}
 RecommendationResultResponse twoVehicle(){Store a=Store.builder().id(1L).code("A").allowedDeliveryHours("All").build(),b=Store.builder().id(2L).code("B").allowedDeliveryHours("All").build();TripDraftStop sa=TripDraftStop.builder().id(1L).store(a).sequenceNo(1).isActive(true).plannedEta(LocalDateTime.of(2026,8,14,9,0)).build(),sb=TripDraftStop.builder().id(2L).store(b).sequenceNo(2).isActive(true).plannedEta(LocalDateTime.of(2026,8,14,10,0)).build();draft.setTotalVolumeM3(new BigDecimal("8"));draft.setTotalWeightKg(new BigDecimal("1600"));Order oa=Order.builder().id(1L).store(a).items(List.of(OrderItem.builder().lineVolumeM3(new BigDecimal("4")).lineWeightKg(new BigDecimal("800")).build())).build(),ob=Order.builder().id(2L).store(b).items(List.of(OrderItem.builder().lineVolumeM3(new BigDecimal("4")).lineWeightKg(new BigDecimal("800")).build())).build();when(drafts.findById(1L)).thenReturn(Optional.of(draft));when(stops.findByTripDraftIdAndIsActiveTrueOrderBySequenceNoAsc(1L)).thenReturn(List.of(sa,sb));when(vehicles.findByIsActiveTrue()).thenReturn(List.of(vehicle(1,"5","1000","10"),vehicle(2,"5","1000","10")));when(orders.findByTripDraftId(1L)).thenReturn(List.of(oa,ob));return service.recommendTop3(1L);}
 @Test @DisplayName("[L1-RC-10] no feasible single vehicle triggers and returns two-vehicle split") void splitFallbackReturnsPair(){RecommendationResultResponse r=twoVehicle();assertAll(()->assertEquals("TWO_VEHICLE",r.getPlanType()),()->assertEquals(2,r.getRecommendations().getFirst().getVehicles().size()));}
 @Test @DisplayName("[L1-RC-11] two-vehicle split keeps each store wholly in one sub-trip") void splitPreservesStoreIntegrity(){RecommendationResultResponse r=twoVehicle();List<VehicleRecommendationResponse.SubTripDto> sub=r.getRecommendations().getFirst().getSubTrips();assertEquals(List.of(List.of(1),List.of(2)),sub.stream().map(VehicleRecommendationResponse.SubTripDto::getStopSequenceNos).toList());}
 @Test @DisplayName("[L1-RC-12] two-vehicle split preserves relative stop order") void splitPreservesStopOrder(){RecommendationResultResponse r=twoVehicle();r.getRecommendations().getFirst().getSubTrips().forEach(s->assertEquals(s.getStopSequenceNos().stream().sorted().toList(),s.getStopSequenceNos()));}
 @Test @DisplayName("[L1-RC-13] pair score applies fifteen-point multi-vehicle penalty") void splitAppliesPenalty(){VehicleRecommendationResponse p=twoVehicle().getRecommendations().getFirst();BigDecimal average=p.getSubTrips().get(0).getSubScore().add(p.getSubTrips().get(1).getSubScore()).divide(new BigDecimal("2"));assertEquals(new BigDecimal("15.00"),average.subtract(p.getTotalScore()));}
}
