package com.elog.service;
import com.elog.dto.request.*;import com.elog.dto.response.*;import com.elog.entity.*;import com.elog.exception.*;import com.elog.repository.*;import com.elog.service.impl.*;
import org.junit.jupiter.api.BeforeEach;import org.junit.jupiter.api.DisplayName;import org.junit.jupiter.api.Test;import org.junit.jupiter.api.extension.ExtendWith;import org.mockito.ArgumentCaptor;import org.mockito.Mock;import org.mockito.junit.jupiter.MockitoExtension;
import java.math.BigDecimal;import java.time.*;import java.util.*;
import static org.junit.jupiter.api.Assertions.*;import static org.mockito.ArgumentMatchers.*;import static org.mockito.Mockito.*;
@ExtendWith(MockitoExtension.class)
class TripServiceImplReport5CatalogTest{
 @Mock TripRepository trips;@Mock TripStopRepository tripStops;@Mock TripDraftRepository drafts;@Mock TripDraftStopRepository draftStops;@Mock VehicleRepository vehicles;@Mock UserRepository users;@Mock ManifestRepository manifests;@Mock OrderItemRepository items;@Mock OrderRepository orders;@Mock TripStateMachine machine;@Mock TripExecutionRepository executions;@Mock PlanningHistoryService history;@Mock TripOutcomeHistoryService outcomeHistory;@Mock SystemConfigRepository configs;
 TripServiceImpl service;TripDraft draft;Vehicle vehicle;User driver,dispatcher;long id;
 @BeforeEach void setup(){service=new TripServiceImpl(trips,tripStops,drafts,draftStops,vehicles,users,manifests,items,orders,machine,executions,history,outcomeHistory,new ConstraintValidationServiceImpl(),configs);draft=TripDraft.builder().id(1L).status("VALIDATED").deliveryDate(LocalDate.of(2026,8,14)).route(Route.builder().id(1L).code("R1").build()).totalVolumeM3(new BigDecimal("5")).totalWeightKg(new BigDecimal("1000")).stops(new ArrayList<>()).build();driver=User.builder().id(2L).username("driver").fullName("Driver").licenseClass(LicenseClass.C).isActive(true).driverStatus(DriverStatus.ACTIVE).roles(Set.of(Role.builder().name("DRIVER").build())).build();dispatcher=User.builder().id(3L).username("dispatcher").fullName("Dispatcher").isActive(true).build();vehicle=Vehicle.builder().id(4L).plateNumber("P4").vehicleType("VAN").maxVolumeM3(new BigDecimal("10")).payloadKg(new BigDecimal("3000")).requiredLicense(LicenseClass.C1).isActive(true).build();}
 TripAssignRequest req(Long driverId){TripAssignRequest r=new TripAssignRequest();r.setVehicleId(4L);r.setDriverId(driverId);return r;}
 void positive(Long driverId){lenient().when(drafts.findById(1L)).thenReturn(Optional.of(draft));lenient().when(vehicles.findById(4L)).thenReturn(Optional.of(vehicle));lenient().when(users.findById(driverId)).thenReturn(Optional.of(driver));lenient().when(users.findByUsername("dispatcher")).thenReturn(Optional.of(dispatcher));lenient().when(trips.save(any())).thenAnswer(i->{Trip t=i.getArgument(0);t.setTripId(10L);return t;});}
 @Test @DisplayName("[L1-TS-01] validated draft assignment creates validated trip with vehicle driver and history")void assignmentCreatesTrip(){positive(2L);TripResponse r=service.assignVehicleAndDriver(1L,req(2L),"dispatcher");assertAll(()->assertEquals(10L,r.getTripId()),()->assertEquals("VALIDATED",r.getStatus()));verify(trips).save(argThat(t->t.getVehicle()==vehicle&&t.getDriver()==driver));verify(history,atLeastOnce()).record(any());}
 @Test @DisplayName("[L1-TS-02] already assigned draft is rejected before vehicle lookup")void assignedDraftRejectedEarly(){when(drafts.findById(1L)).thenReturn(Optional.of(draft));when(trips.existsByTripDraftId(1L)).thenReturn(true);BusinessException e=assertThrows(BusinessException.class,()->service.assignVehicleAndDriver(1L,req(2L),"dispatcher"));assertEquals(ErrorCode.TRIP_DRAFT_ALREADY_ASSIGNED,e.getErrorCode());verifyNoInteractions(vehicles);}
 @Test @DisplayName("[L1-TS-03] missing request driver falls back to vehicle fixed driver")void fixedDriverFallback(){vehicle.setAssignedDriver(driver);positive(2L);TripResponse r=service.assignVehicleAndDriver(1L,req(null),"dispatcher");assertEquals(10L,r.getTripId());verify(users).findById(2L);}
 @Test @DisplayName("[L1-TS-04] nonvalidated draft rejects assignment")void nonvalidatedDraftRejected(){draft.setStatus("DRAFT");when(drafts.findById(1L)).thenReturn(Optional.of(draft));BusinessException e=assertThrows(BusinessException.class,()->service.assignVehicleAndDriver(1L,req(2L),"dispatcher"));assertEquals(ErrorCode.TRIP_DRAFT_NOT_VALIDATED,e.getErrorCode());}
 @Test @DisplayName("[L1-TS-05] missing vehicle rejects assignment before trip save")void missingVehicleRejected(){when(drafts.findById(1L)).thenReturn(Optional.of(draft));when(vehicles.findById(4L)).thenReturn(Optional.empty());BusinessException e=assertThrows(BusinessException.class,()->service.assignVehicleAndDriver(1L,req(2L),"dispatcher"));assertEquals(ErrorCode.VEHICLE_NOT_FOUND,e.getErrorCode());verify(trips,never()).save(any());}
 @Test @DisplayName("[L1-TS-06] vehicle conflict rejects assignment")void vehicleConflictRejected(){positive(2L);when(trips.existsByVehicleIdAndDeliveryDateAndStatusIn(eq(4L),any(),any())).thenReturn(true);BusinessException e=assertThrows(BusinessException.class,()->service.assignVehicleAndDriver(1L,req(2L),"dispatcher"));assertEquals(ErrorCode.VEHICLE_CONFLICT,e.getErrorCode());verify(trips,never()).save(any());}
 @Test @DisplayName("[L1-TS-07] missing driver rejects assignment before trip save")void missingDriverRejected(){when(drafts.findById(1L)).thenReturn(Optional.of(draft));when(vehicles.findById(4L)).thenReturn(Optional.of(vehicle));when(users.findById(2L)).thenReturn(Optional.empty());BusinessException e=assertThrows(BusinessException.class,()->service.assignVehicleAndDriver(1L,req(2L),"dispatcher"));assertEquals(ErrorCode.DRIVER_NOT_FOUND,e.getErrorCode());verify(trips,never()).save(any());}
 @Test @DisplayName("[L1-TS-08] insufficient driver license rejects assignment")void licenseMismatchRejected(){driver.setLicenseClass(LicenseClass.B);positive(2L);BusinessException e=assertThrows(BusinessException.class,()->service.assignVehicleAndDriver(1L,req(2L),"dispatcher"));assertEquals(ErrorCode.DRIVER_LICENSE_INCOMPATIBLE,e.getErrorCode());verify(trips,never()).save(any());}
 @Test @DisplayName("[L1-TS-09] driver conflict rejects assignment")void driverConflictRejected(){positive(2L);when(trips.existsByDriverIdAndDeliveryDateAndStatusIn(eq(2L),any(),any())).thenReturn(true);BusinessException e=assertThrows(BusinessException.class,()->service.assignVehicleAndDriver(1L,req(2L),"dispatcher"));assertEquals(ErrorCode.DRIVER_CONFLICT,e.getErrorCode());verify(trips,never()).save(any());}
 TripSplitResponse split(){List<TripDraftStop> ss=new ArrayList<>();for(int n=1;n<=4;n++){Store s=Store.builder().id((long)n).code("S"+n).latitude(21.0+n/100.0).longitude(105.0+n/100.0).allowedDeliveryHours("All").build();ss.add(TripDraftStop.builder().id((long)n).tripDraft(draft).store(s).sequenceNo(n).isActive(true).build());}draft.setStops(ss);Vehicle v2=Vehicle.builder().id(5L).plateNumber("P5").vehicleType("VAN").maxVolumeM3(new BigDecimal("10")).payloadKg(new BigDecimal("3000")).requiredLicense(LicenseClass.C1).isActive(true).build();User d2=User.builder().id(6L).fullName("Driver2").licenseClass(LicenseClass.C).isActive(true).driverStatus(DriverStatus.ACTIVE).roles(Set.of(Role.builder().name("DRIVER").build())).build();when(drafts.findById(1L)).thenReturn(Optional.of(draft));when(users.findByUsername("dispatcher")).thenReturn(Optional.of(dispatcher));when(draftStops.findByTripDraftIdAndIsActiveTrueOrderBySequenceNoAsc(1L)).thenReturn(ss);for(TripDraftStop s:ss){when(draftStops.findById(s.getId())).thenReturn(Optional.of(s));when(items.findByStopForManifest(s.getStore().getId(),1L)).thenReturn(List.of(OrderItem.builder().lineVolumeM3(BigDecimal.ONE).lineWeightKg(BigDecimal.TEN).build()));}when(vehicles.findById(4L)).thenReturn(Optional.of(vehicle));when(vehicles.findById(5L)).thenReturn(Optional.of(v2));when(users.findById(2L)).thenReturn(Optional.of(driver));when(users.findById(6L)).thenReturn(Optional.of(d2));when(trips.save(any())).thenAnswer(i->{Trip t=i.getArgument(0);t.setTripId(++id);return t;});TripSplitAssignRequest r=new TripSplitAssignRequest(List.of(new TripSplitAssignRequest.SplitAssignment(4L,2L,List.of(2L,1L)),new TripSplitAssignRequest.SplitAssignment(5L,6L,List.of(4L,3L))));return service.assignSplit(1L,r,"dispatcher");}
 @Test @DisplayName("[L1-TS-10] split assignment creates two trips for one draft")void splitCreatesTwoTrips(){TripSplitResponse r=split();assertEquals(2,r.getTripsCreated());verify(trips,times(2)).save(any());}
 @Test @DisplayName("[L1-TS-11] split rejects a nonvalidated draft")void splitRejectsDraftState(){draft.setStatus("DRAFT");when(drafts.findById(1L)).thenReturn(Optional.of(draft));TripSplitAssignRequest r=new TripSplitAssignRequest(List.of());BusinessException e=assertThrows(BusinessException.class,()->service.assignSplit(1L,r,"dispatcher"));assertEquals(ErrorCode.TRIP_DRAFT_NOT_VALIDATED,e.getErrorCode());}
 @Test @DisplayName("[L1-TS-12] split preserves original stop order within each subtrip")void splitPreservesStopOrder(){split();ArgumentCaptor<List<TripStop>> cap=ArgumentCaptor.forClass(List.class);verify(tripStops,times(2)).saveAll(cap.capture());assertEquals(List.of(List.of(1,2),List.of(3,4)),cap.getAllValues().stream().map(group->group.stream().map(TripStop::getSequenceOrder).toList()).toList());}
}
