package com.elog.exception;

import lombok.Getter;

/**
 * Application-level error codes — map 1:1 to the codes in
 * docs/api-conventions.md.
 * Used in ApiErrorResponse.code field so frontend can handle errors
 * programmatically.
 */
@Getter
public enum ErrorCode {

    // Resource errors
    RESOURCE_NOT_FOUND("RESOURCE_NOT_FOUND"),
    INVALID_REQUEST("INVALID_REQUEST"),
    ACCESS_DENIED("ACCESS_DENIED"),
    INVALID_CREDENTIALS("INVALID_CREDENTIALS"),
    TOKEN_EXPIRED("TOKEN_EXPIRED"),
    TOKEN_INVALID("TOKEN_INVALID"),
    ACCOUNT_DISABLED("ACCOUNT_DISABLED"),

    // Business rule violations
    PRODUCT_NOT_FOUND("PRODUCT_NOT_FOUND"),
    PRODUCT_SKU_DUPLICATE("PRODUCT_SKU_DUPLICATE"),
    PRODUCT_SKU_IMMUTABLE("PRODUCT_SKU_IMMUTABLE"),

    STORE_NOT_FOUND("STORE_NOT_FOUND"),
    STORE_CODE_DUPLICATE("STORE_CODE_DUPLICATE"),
    STORE_ACTIVE_ROUTE("STORE_ACTIVE_ROUTE"),
    INVALID_COORDINATES("INVALID_COORDINATES"),
    STORE_NOT_ASSIGNABLE("STORE_NOT_ASSIGNABLE"), // BR-02
    PROVINCE_NOT_FOUND("PROVINCE_NOT_FOUND"),
    DISTRICT_NOT_FOUND("DISTRICT_NOT_FOUND"),
    WARD_NOT_FOUND("WARD_NOT_FOUND"),
    INVALID_ADDRESS("INVALID_ADDRESS"),

    // Route business rules
    ROUTE_NOT_FOUND("ROUTE_NOT_FOUND"),
    ROUTE_CODE_DUPLICATE("ROUTE_CODE_DUPLICATE"),
    ROUTE_STOP_DUPLICATE("ROUTE_STOP_DUPLICATE"),
    ROUTE_INSUFFICIENT_STOPS("ROUTE_INSUFFICIENT_STOPS"),
    ROUTE_STOP_NOT_FOUND("ROUTE_STOP_NOT_FOUND"),
    ROUTE_STOP_REORDER_INVALID("ROUTE_STOP_REORDER_INVALID"),
    STORE_INACTIVE("STORE_INACTIVE"),

    // Vehicle business rules
    VEHICLE_NOT_FOUND("VEHICLE_NOT_FOUND"),
    VEHICLE_PLATE_DUPLICATE("VEHICLE_PLATE_DUPLICATE"),
    VEHICLE_CODE_DUPLICATE("VEHICLE_CODE_DUPLICATE"),
    DRIVER_LICENSE_INCOMPATIBLE("DRIVER_LICENSE_INCOMPATIBLE"),

    CAPACITY_EXCEEDED("CAPACITY_EXCEEDED"), // BR-03
    FLEET_CAPACITY_INSUFFICIENT("FLEET_CAPACITY_INSUFFICIENT"), // BR-08
    INVALID_STATE_TRANSITION("INVALID_STATE_TRANSITION"), // DC-01
    EPOD_REQUIRED("EPOD_REQUIRED"), // BR-11
    INVALID_CAPACITY_RATIO("INVALID_CAPACITY_RATIO"),

    // Import
    EXCEL_PARSE_ERROR("EXCEL_PARSE_ERROR"),
    DUPLICATE_DELIVERY_DATE("DUPLICATE_DELIVERY_DATE"),
    INVALID_FILE_FORMAT("INVALID_FILE_FORMAT"),
    FILE_TOO_LARGE("FILE_TOO_LARGE"),

    // Trip Draft (US-10)
    TRIP_DRAFT_NOT_FOUND("TRIP_DRAFT_NOT_FOUND"),
    TRIP_DRAFT_LOCKED("TRIP_DRAFT_LOCKED"),

    // Trip Draft Review (US-11)
    CANNOT_ACTIVATE_EMPTY_STOP("CANNOT_ACTIVATE_EMPTY_STOP"),
    NO_ACTIVE_STOP("NO_ACTIVE_STOP"),
    ETA_NOT_CALCULATED("ETA_NOT_CALCULATED"),
    ETA_MISSING_COORDINATES("ETA_MISSING_COORDINATES"),
    ALREADY_CONFIRMED("ALREADY_CONFIRMED"),

    // Capacity Validation (US-12)
    TRIP_DRAFT_NOT_CONFIRMED("TRIP_DRAFT_NOT_CONFIRMED"),
    ALREADY_VALIDATED("ALREADY_VALIDATED"),
    NO_ITEMS_TO_VALIDATE("NO_ITEMS_TO_VALIDATE"),
    NO_ACTIVE_VEHICLE("NO_ACTIVE_VEHICLE"),

    // LIFO Manifest (US-13)
    TRIP_DRAFT_NOT_VALIDATED("TRIP_DRAFT_NOT_VALIDATED"),
    MANIFEST_ALREADY_EXISTS("MANIFEST_ALREADY_EXISTS"),
    MANIFEST_NOT_FOUND("MANIFEST_NOT_FOUND"),

    // Vehicle Assignment (US-15)
    VEHICLE_NOT_ELIGIBLE("VEHICLE_NOT_ELIGIBLE"),
    VEHICLE_CONFLICT("VEHICLE_CONFLICT"),
    DRIVER_CONFLICT("DRIVER_CONFLICT"),
    DRIVER_NOT_FOUND("DRIVER_NOT_FOUND"),
    INSUFFICIENT_FLEET("INSUFFICIENT_FLEET"),
    TRIP_DRAFT_ALREADY_ASSIGNED("TRIP_DRAFT_ALREADY_ASSIGNED"),

    // Dispatch (US-16)
    TRIP_NOT_FOUND("TRIP_NOT_FOUND"),
    TRIP_LOCKED("TRIP_LOCKED"),
    TRIP_COMPLETED("TRIP_COMPLETED"),
    INVALID_TRIP_TRANSITION("INVALID_TRIP_TRANSITION"),
    FLEET_CAPACITY_SHORTFALL("FLEET_CAPACITY_SHORTFALL"),
    HANDOVER_SLIP_NOT_AVAILABLE("HANDOVER_SLIP_NOT_AVAILABLE"),

    // Trip Monitoring (US-17)
    NOT_YOUR_TRIP("NOT_YOUR_TRIP"),
    TRIP_STOP_NOT_FOUND("TRIP_STOP_NOT_FOUND"),
    STOP_NOT_PENDING("STOP_NOT_PENDING"),
    STOP_NOT_IN_PROGRESS("STOP_NOT_IN_PROGRESS"),
    STOP_ALREADY_DONE("STOP_ALREADY_DONE"),
    PREVIOUS_STOP_NOT_DONE("PREVIOUS_STOP_NOT_DONE"),

    // Exception Management (US-18)
    REJECTION_ALREADY_RECORDED("REJECTION_ALREADY_RECORDED"),
    EXCEPTION_NOT_FOUND("EXCEPTION_NOT_FOUND"),
    EXCEPTION_ALREADY_RESOLVED("ALREADY_RESOLVED"),

    // Validation
    FIELD_REQUIRED("Field cannot be blank"),
    INVALID_FORMAT("Invalid format"),
    INVALID_SIZE("Invalid size"),
    USERNAME_INVALID("Username must be 3-50 characters and contain only letters, numbers, and underscores"),
    PASSWORD_INVALID(
            "Password must be at least 8 characters, containing at least 1 uppercase letter, 1 number, and 1 special character"),

    // Recommendation Engine
    NO_FEASIBLE_PLAN("NO_FEASIBLE_PLAN"),

    // Auth & Permission
    UNAUTHORIZED_ACCESS("UNAUTHORIZED_ACCESS"),

    // Generic
    VALIDATION_FAILED("VALIDATION_FAILED"),
    INTERNAL_ERROR("INTERNAL_ERROR");

    private final String code;

    ErrorCode(String code) {
        this.code = code;
    }
}
