-- V16__manifest_schema.sql
-- US-13 LIFO Manifest

CREATE TABLE manifests (
    manifest_id     BIGINT        AUTO_INCREMENT PRIMARY KEY,
    trip_draft_id   BIGINT        NOT NULL,
    trip_id         BIGINT        NULL,
    generated_at    DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    generated_by    BIGINT        NOT NULL,
    total_lines     INT           NOT NULL DEFAULT 0,
    total_weight_kg DECIMAL(10,3) NOT NULL DEFAULT 0,
    total_volume_m3 DECIMAL(10,6) NOT NULL DEFAULT 0,
    CONSTRAINT fk_manifest_tripdraft
        FOREIGN KEY (trip_draft_id) REFERENCES trip_drafts(id),
    CONSTRAINT fk_manifest_generated_by
        FOREIGN KEY (generated_by) REFERENCES users(id),
    CONSTRAINT uq_manifest_tripdraft UNIQUE (trip_draft_id)
);

CREATE TABLE manifest_lines (
    line_id             BIGINT          AUTO_INCREMENT PRIMARY KEY,
    manifest_id         BIGINT          NOT NULL,
    trip_draft_stop_id  BIGINT          NOT NULL,
    order_item_id       BIGINT          NOT NULL,
    lifo_sequence       INT             NOT NULL CHECK (lifo_sequence > 0),
    stop_sequence_no    INT             NOT NULL,
    store_code          VARCHAR(20)     NOT NULL,
    store_name          VARCHAR(100)    NOT NULL,
    product_code        VARCHAR(30)     NOT NULL,
    product_name        VARCHAR(150)    NOT NULL,
    quantity            INT             NOT NULL CHECK (quantity > 0),
    unit_volume_m3      DECIMAL(10,6)   NOT NULL,
    unit_weight_kg      DECIMAL(8,3)    NOT NULL,
    line_volume_m3      DECIMAL(10,6)   NOT NULL,
    line_weight_kg      DECIMAL(10,3)   NOT NULL,
    CONSTRAINT fk_ml_manifest     FOREIGN KEY (manifest_id)        REFERENCES manifests(manifest_id),
    CONSTRAINT fk_ml_draftstop    FOREIGN KEY (trip_draft_stop_id) REFERENCES trip_draft_stops(id),
    CONSTRAINT fk_ml_orderitem    FOREIGN KEY (order_item_id)      REFERENCES order_items(id)
);

-- Index tối ưu render manifest
CREATE INDEX idx_ml_manifest_lifo
    ON manifest_lines (manifest_id, lifo_sequence);

CREATE INDEX idx_ml_manifest_stop
    ON manifest_lines (manifest_id, stop_sequence_no, lifo_sequence);

-- ============================================================
-- SEED DATA — US-13 LIFO Manifest
-- ============================================================

-- ────────────────────────────────────────────────────────────
-- 1. Update TripDraft #1 → simulate US-11 confirm + US-12 validate
--    (TripDraft #2 giữ nguyên DRAFT để test negative case)
-- ────────────────────────────────────────────────────────────
UPDATE trip_drafts SET
    status                = 'VALIDATED',
    planned_departure_time = '07:00:00',
    confirmed_at          = '2026-03-15 14:00:00',
    confirmed_by          = 2,
    volume_check_result   = 'PASS',
    weight_check_result   = 'PASS',
    validated_at          = '2026-03-15 14:05:00',
    validated_by          = 2
WHERE id = 1;

-- ────────────────────────────────────────────────────────────
-- 2. Seed Manifest cho TripDraft #1
--    Generated by dispatcher01 (user_id=2)
--
--    TripDraft #1 (RT-001): 2 active stops
--      Stop 1 (tds_id=1, seq=1): ST-001 → OrderItems #1 (REF-SAM-300 ×2), #2 (TV-SAM-55 ×1)
--      Stop 2 (tds_id=2, seq=2): ST-002 → OrderItem  #3 (GEN-DNY-5K  ×3)
--
--    LIFO reverse → [Stop-2, Stop-1]:
--      lifo_seq 1 = Stop-2 (ST-002) → GEN-DNY-5K  ×3 (xếp vào đầu tiên, sâu nhất)
--      lifo_seq 2 = Stop-1 (ST-001) → REF-SAM-300 ×2
--      lifo_seq 3 = Stop-1 (ST-001) → TV-SAM-55   ×1 (xếp vào cuối cùng, gần cửa xe)
--
--    Totals: weight = 570.000 + 130.000 + 28.500 = 728.500 kg
--            volume = 0.841500 + 1.428000 + 0.199260 = 2.468760 m³
-- ────────────────────────────────────────────────────────────
INSERT INTO manifests (manifest_id, trip_draft_id, trip_id, generated_at, generated_by, total_lines, total_weight_kg, total_volume_m3) VALUES
(1, 1, NULL, '2026-03-15 14:10:00', 2, 3, 728.500, 2.468760);

-- ────────────────────────────────────────────────────────────
-- 3. Seed ManifestLines — LIFO order
-- ────────────────────────────────────────────────────────────
INSERT INTO manifest_lines (line_id, manifest_id, trip_draft_stop_id, order_item_id, lifo_sequence, stop_sequence_no, store_code, store_name, product_code, product_name, quantity, unit_volume_m3, unit_weight_kg, line_volume_m3, line_weight_kg) VALUES
-- Stop 2 (seq=2, ST-002) → xếp vào đầu tiên (sâu nhất trong xe)
(1, 1, 2, 3, 1, 2, 'ST-002', 'Cửa hàng Quận 3', 'GEN-DNY-5K', 'Máy phát điện Denyo 5KVA', 3, 0.280500, 190.000, 0.841500, 570.000),
-- Stop 1 (seq=1, ST-001) → xếp vào cuối (gần cửa xe)
(2, 1, 1, 1, 2, 1, 'ST-001', 'Cửa hàng Quận 1', 'REF-SAM-300', 'Tủ lạnh Samsung 300L', 2, 0.714000, 65.000, 1.428000, 130.000),
(3, 1, 1, 2, 3, 1, 'ST-001', 'Cửa hàng Quận 1', 'TV-SAM-55', 'Tivi Samsung 55" Crystal UHD', 1, 0.199260, 28.500, 0.199260, 28.500);
