-- V58__seed_product_classification_from_excel_v1.sql
-- Seed product classification fields (brand, product_group, product_type, capacity_value)
-- from Du_lieu_mo_phong_sap_lenh_v1.xlsx (sheet 01_DM_VatTu) matching by SKU.

UPDATE products SET brand = '1.TOSHIBA', product_group = 'Tủ lạnh', product_type = '1.Tủ lạnh', capacity_value = 515.00 WHERE sku = 'TOSTLR677WI';
UPDATE products SET brand = '1.TOSHIBA', product_group = 'Tủ lạnh', product_type = '1.Tủ lạnh', capacity_value = 515.00 WHERE sku = 'TOSTLR677WIMG';
UPDATE products SET brand = '1.TOSHIBA', product_group = 'Tủ lạnh', product_type = '1.Tủ lạnh', capacity_value = 482.00 WHERE sku = 'TOSTLR696WI';
UPDATE products SET brand = '2.SHARP', product_group = 'Tủ lạnh', product_type = '1.Tủ lạnh', capacity_value = 362.00 WHERE sku = 'SHATLFX420VSL';
UPDATE products SET brand = '1.TOSHIBA', product_group = 'Máy giặt', product_type = '2.Máy giặt', capacity_value = 10.00 WHERE sku = 'TOSMGM1100JV';
UPDATE products SET brand = '4.HITACHI', product_group = 'Tủ lạnh', product_type = '1.Tủ lạnh', capacity_value = 569.00 WHERE sku = 'HITLWB640GBK';
UPDATE products SET brand = '4.HITACHI', product_group = 'Tủ lạnh', product_type = '1.Tủ lạnh', capacity_value = 569.00 WHERE sku = 'HITLWB640PGV1GMG';
UPDATE products SET brand = '1.TOSHIBA', product_group = 'Tủ lạnh', product_type = '1.Tủ lạnh', capacity_value = 515.00 WHERE sku = 'TOSTLR675WI';
UPDATE products SET brand = '2.SHARP', product_group = 'Tủ lạnh', product_type = '1.Tủ lạnh', capacity_value = 626.00 WHERE sku = 'SHATLFX630';
UPDATE products SET brand = '1.TOSHIBA', product_group = 'Máy giặt', product_type = '2.Máy giặt', capacity_value = 10.00 WHERE sku = 'TOSMGM1000FV';
UPDATE products SET brand = 'DAIKIN', product_group = 'Điều hoà', product_type = '4.Điều hoà', capacity_value = 0.00 WHERE sku = 'DAIKDLFTKB25ZVMV';
UPDATE products SET brand = '3.PANASONIC', product_group = 'Máy giặt', product_type = '2.Máy giặt', capacity_value = 10.00 WHERE sku = 'PANMGNA10FA1LVT';
UPDATE products SET brand = '1.TOSHIBA', product_group = 'Tủ lạnh', product_type = '1.Tủ lạnh', capacity_value = 180.00 WHERE sku = 'TOSTLRT234WE';
UPDATE products SET brand = '5.ELECTROLUX', product_group = 'Máy giặt', product_type = '2.Máy giặt', capacity_value = 10.00 WHERE sku = 'ELEMGEWF1023P5SC';
UPDATE products SET brand = '3.PANASONIC', product_group = 'Máy giặt', product_type = '2.Máy giặt', capacity_value = 10.00 WHERE sku = 'PANMFF10S10BRV';
UPDATE products SET brand = '1.TOSHIBA', product_group = 'Máy giặt', product_type = '2.Máy giặt', capacity_value = 11.00 WHERE sku = 'TOSMGAWDM1100JV';
UPDATE products SET brand = '1.TOSHIBA', product_group = 'Tủ lạnh', product_type = '1.Tủ lạnh', capacity_value = 338.00 WHERE sku = 'TOSTLRT468WE';
UPDATE products SET brand = '2.SHARP', product_group = 'Tủ lạnh', product_type = '1.Tủ lạnh', capacity_value = 330.00 WHERE sku = 'SHATLXP352AEDS';
UPDATE products SET brand = 'DAIKIN', product_group = 'Điều hoà', product_type = '4.Điều hoà', capacity_value = 0.00 WHERE sku = 'DAIKDLFTF25XAV1V';
UPDATE products SET brand = '3.PANASONIC', product_group = 'Tủ lạnh', product_type = '1.Tủ lạnh', capacity_value = 251.00 WHERE sku = 'PANTLTLSP275CP';
UPDATE products SET brand = 'DAIKIN', product_group = 'Điều hoà', product_type = '4.Điều hoà', capacity_value = 0.00 WHERE sku = 'DAIKDLFTKB35ZVMV';
UPDATE products SET brand = '3.PANASONIC', product_group = 'Máy giặt', product_type = '2.Máy giặt', capacity_value = 9.00 WHERE sku = 'PANMF90S10BRV';
UPDATE products SET brand = '4.HITACHI', product_group = 'Tủ lạnh', product_type = '1.Tủ lạnh', capacity_value = 586.00 WHERE sku = 'HITLRW690PGV7';
UPDATE products SET brand = '5.ELECTROLUX', product_group = 'Máy giặt', product_type = '2.Máy giặt', capacity_value = 10.00 WHERE sku = 'ELEMGEWF1024D3SC';
UPDATE products SET brand = '1.TOSHIBA', product_group = 'Máy giặt', product_type = '2.Máy giặt', capacity_value = 11.50 WHERE sku = 'TOSTLTW115A2V';
UPDATE products SET brand = '3.PANASONIC', product_group = 'Tủ lạnh', product_type = '1.Tủ lạnh', capacity_value = 465.00 WHERE sku = 'PANTLBX471GPKV';
UPDATE products SET brand = '1.TOSHIBA', product_group = 'Tủ lạnh', product_type = '1.Tủ lạnh', capacity_value = 453.00 WHERE sku = 'TOSTLRT535WEA';
UPDATE products SET brand = '1.TOSHIBA', product_group = 'Tủ lạnh', product_type = '1.Tủ lạnh', capacity_value = 262.00 WHERE sku = 'TOSTLRT252WE';
UPDATE products SET brand = 'DAIKIN', product_group = 'Điều hoà', product_type = '4.Điều hoà', capacity_value = 0.00 WHERE sku = 'DAIKDLFTF35XAV1V';
UPDATE products SET brand = '1.TOSHIBA', product_group = 'Máy giặt', product_type = '2.Máy giặt', capacity_value = 13.00 WHERE sku = 'TOSMGDUK1300KV';
UPDATE products SET brand = '3.PANASONIC', product_group = 'Máy giặt', product_type = '2.Máy giặt', capacity_value = 10.00 WHERE sku = 'PANMGNF100A9DRV';
UPDATE products SET brand = '1.TOSHIBA', product_group = 'Tủ lạnh', product_type = '1.Tủ lạnh', capacity_value = 452.00 WHERE sku = 'TOSTLRT559WE';
UPDATE products SET brand = '1.TOSHIBA', product_group = 'Tủ lạnh', product_type = '1.Tủ lạnh', capacity_value = 471.00 WHERE sku = 'TOSTLRF606WI-PMV(60)-AG';
UPDATE products SET brand = '2.SHARP', product_group = 'Tủ lạnh', product_type = '1.Tủ lạnh', capacity_value = 181.00 WHERE sku = 'SHATLX198VDG';
UPDATE products SET brand = '3.PANASONIC', product_group = 'Tủ lạnh', product_type = '1.Tủ lạnh', capacity_value = 420.00 WHERE sku = 'PANTLBX421GPKV';
UPDATE products SET brand = '2.SHARP', product_group = 'Tủ lạnh', product_type = '1.Tủ lạnh', capacity_value = 678.00 WHERE sku = 'SHATLFX688VG';
UPDATE products SET brand = '1.TOSHIBA', product_group = 'Máy giặt', product_type = '2.Máy giặt', capacity_value = 9.00 WHERE sku = 'TOSMGM905BV';
UPDATE products SET brand = '3.PANASONIC', product_group = 'Máy giặt', product_type = '2.Máy giặt', capacity_value = 9.00 WHERE sku = 'PANMGNF90A9DRV';
UPDATE products SET brand = '5.ELECTROLUX', product_group = 'Máy sấy', product_type = '3.Máy sấy', capacity_value = 9.00 WHERE sku = 'ELEMSEDV904N3SC';
UPDATE products SET brand = '5.ELECTROLUX', product_group = 'Máy giặt', product_type = '2.Máy giặt', capacity_value = 10.00 WHERE sku = 'ELEMGEWF1023P5WC';
UPDATE products SET brand = '3.PANASONIC', product_group = 'Tủ lạnh', product_type = '1.Tủ lạnh', capacity_value = 325.00 WHERE sku = 'PANTLBC361VGMV';
UPDATE products SET brand = 'AUFIT', product_group = 'Điều hoà', product_type = '4.Điều hoà', capacity_value = 0.00 WHERE sku = 'AFW09FHA4DI-3VN';
UPDATE products SET brand = '3.PANASONIC', product_group = 'Máy giặt', product_type = '2.Máy giặt', capacity_value = 9.00 WHERE sku = 'PANMGNA90FA1LVT';
UPDATE products SET brand = '1.TOSHIBA', product_group = 'Tủ lạnh', product_type = '1.Tủ lạnh', capacity_value = 610.00 WHERE sku = 'TOSTLR611WI';
UPDATE products SET brand = '3.PANASONIC', product_group = 'Tủ lạnh', product_type = '1.Tủ lạnh', capacity_value = 580.00 WHERE sku = 'PANTLDZ601VGKV';
UPDATE products SET brand = '2.SHARP', product_group = 'Tủ lạnh', product_type = '1.Tủ lạnh', capacity_value = 352.00 WHERE sku = 'SHATLXP352AESL';
UPDATE products SET brand = '1.TOSHIBA', product_group = 'Tủ lạnh', product_type = '1.Tủ lạnh', capacity_value = 360.00 WHERE sku = 'TOSTLR405WEA';
UPDATE products SET brand = '3.PANASONIC', product_group = 'Máy giặt', product_type = '2.Máy giặt', capacity_value = 11.50 WHERE sku = 'PANMGNAV115FA1LV';
UPDATE products SET brand = '2.SHARP', product_group = 'Tủ lạnh', product_type = '1.Tủ lạnh', capacity_value = 472.00 WHERE sku = 'SHATLSBX440VGBK';
UPDATE products SET brand = '5.ELECTROLUX', product_group = 'Máy giặt', product_type = '2.Máy giặt', capacity_value = 9.00 WHERE sku = 'ELEMGEWF9023P5SC';
UPDATE products SET brand = '3.PANASONIC', product_group = 'Máy giặt', product_type = '2.Máy giặt', capacity_value = 8.20 WHERE sku = 'PANMGNF82Y01DRV';
UPDATE products SET brand = '2.SHARP', product_group = 'Tủ lạnh', product_type = '1.Tủ lạnh', capacity_value = 215.00 WHERE sku = 'SHATLX215VDG';
UPDATE products SET brand = '3.PANASONIC', product_group = 'Tủ lạnh', product_type = '1.Tủ lạnh', capacity_value = 536.00 WHERE sku = 'PANTLCW530XMMV';
UPDATE products SET brand = '5.ELECTROLUX', product_group = 'Máy giặt', product_type = '2.Máy giặt', capacity_value = 9.00 WHERE sku = 'ELEMGEWF9023P5WC';
UPDATE products SET brand = '5.ELECTROLUX', product_group = 'Máy sấy', product_type = '3.Máy sấy', capacity_value = 9.00 WHERE sku = 'ELEMSEDV904H3WC';
UPDATE products SET brand = '5.ELECTROLUX', product_group = 'Máy sấy', product_type = '3.Máy sấy', capacity_value = 8.00 WHERE sku = 'ELEMSEDV804H3WC';
UPDATE products SET brand = '1.TOSHIBA', product_group = 'Máy sấy', product_type = '3.Máy sấy', capacity_value = 8.00 WHERE sku = 'TOSMSH80SEV';
UPDATE products SET brand = '1.TOSHIBA', product_group = 'Tủ lạnh', product_type = '1.Tủ lạnh', capacity_value = 355.00 WHERE sku = 'TOSTLRB410WESG';
UPDATE products SET brand = '2.SHARP', product_group = 'Tủ lạnh', product_type = '1.Tủ lạnh', capacity_value = 382.00 WHERE sku = 'SHATLXP382AEDS';
UPDATE products SET brand = '2.SHARP', product_group = 'Máy giặt', product_type = '2.Máy giặt', capacity_value = 12.50 WHERE sku = 'SHAMGESTM125BK';
UPDATE products SET brand = '3.PANASONIC', product_group = 'Tủ lạnh', product_type = '1.Tủ lạnh', capacity_value = 300.00 WHERE sku = 'PANTLBV331CP';
UPDATE products SET brand = '3.PANASONIC', product_group = 'Tủ lạnh', product_type = '1.Tủ lạnh', capacity_value = 601.00 WHERE sku = 'PANTLDZ601YGKV';
UPDATE products SET brand = '3.PANASONIC', product_group = 'Máy giặt', product_type = '2.Máy giặt', capacity_value = 11.00 WHERE sku = 'PANMGNF110A9DRV';
UPDATE products SET brand = '2.SHARP', product_group = 'Máy giặt', product_type = '2.Máy giặt', capacity_value = 10.00 WHERE sku = 'SHAMGESY100HVS';
UPDATE products SET brand = '1.TOSHIBA', product_group = 'Tủ lạnh', product_type = '1.Tủ lạnh', capacity_value = 620.00 WHERE sku = 'TOSTLRS780WI';
UPDATE products SET brand = '2.SHARP', product_group = 'Máy giặt', product_type = '2.Máy giặt', capacity_value = 9.00 WHERE sku = 'SHAMGESY90HVS';
UPDATE products SET brand = '3.PANASONIC', product_group = 'Tủ lạnh', product_type = '1.Tủ lạnh', capacity_value = 551.00 WHERE sku = 'PANTLNR-X561GB-VN';
UPDATE products SET brand = '2.SHARP', product_group = 'Máy giặt', product_type = '2.Máy giặt', capacity_value = 11.00 WHERE sku = 'SHAMGESFM110CBSB';
UPDATE products SET brand = '3.PANASONIC', product_group = 'Tủ lạnh', product_type = '1.Tủ lạnh', capacity_value = 551.00 WHERE sku = 'PANTLNR-X561BK-VN';
UPDATE products SET brand = '1.TOSHIBA', product_group = 'Máy giặt', product_type = '2.Máy giặt', capacity_value = 16.00 WHERE sku = 'TOSMGDUM1600';
UPDATE products SET brand = 'DAIKIN', product_group = 'Điều hoà', product_type = '4.Điều hoà', capacity_value = 0.00 WHERE sku = 'DAIKDLFTHF35XVMV';
UPDATE products SET brand = '2.SHARP', product_group = 'Máy giặt', product_type = '2.Máy giặt', capacity_value = 7.50 WHERE sku = 'SHAMGESY75HVS';
UPDATE products SET brand = 'DAIKIN', product_group = 'Điều hoà', product_type = '4.Điều hoà', capacity_value = 0.00 WHERE sku = 'DAIKDLFTKB35YVMV';
UPDATE products SET brand = '1.TOSHIBA', product_group = 'Máy sấy', product_type = '3.Máy sấy', capacity_value = 9.00 WHERE sku = 'TOSTDT21B90HWV(MG)';
UPDATE products SET brand = '2.SHARP', product_group = 'Tủ lạnh', product_type = '1.Tủ lạnh', capacity_value = 382.00 WHERE sku = 'SHATLXP382AESL';
UPDATE products SET brand = '5.ELECTROLUX', product_group = 'Máy sấy', product_type = '3.Máy sấy', capacity_value = 8.00 WHERE sku = 'ELEMSEDH803J5SC';
UPDATE products SET brand = '1.TOSHIBA', product_group = 'Máy giặt', product_type = '2.Máy giặt', capacity_value = 10.00 WHERE sku = 'TOSMGM1100PV';
UPDATE products SET brand = '2.SHARP', product_group = 'Tủ lạnh', product_type = '1.Tủ lạnh', capacity_value = 530.00 WHERE sku = 'SHATLSBX530WDDG';
UPDATE products SET brand = '1.TOSHIBA', product_group = 'Tủ lạnh', product_type = '1.Tủ lạnh', capacity_value = 435.00 WHERE sku = 'TOSTLRT435WEA';
UPDATE products SET brand = '1.TOSHIBA', product_group = 'Tủ lạnh', product_type = '1.Tủ lạnh', capacity_value = 895.00 WHERE sku = 'TOSTLRF895WIA';
UPDATE products SET brand = '3.PANASONIC', product_group = 'Máy giặt', product_type = '2.Máy giặt', capacity_value = 11.50 WHERE sku = 'PANMGNFD115X3BV';
UPDATE products SET brand = '5.ELECTROLUX', product_group = 'Máy sấy', product_type = '3.Máy sấy', capacity_value = 8.00 WHERE sku = 'ELEMSEDH803J5WC';
UPDATE products SET brand = 'DAIKIN', product_group = 'Điều hoà', product_type = '4.Điều hoà', capacity_value = 0.00 WHERE sku = 'DAIKDLFTKB50ZVMV';
UPDATE products SET brand = '2.SHARP', product_group = 'Máy giặt', product_type = '2.Máy giặt', capacity_value = 8.50 WHERE sku = 'SHAMGESY85HVS';
UPDATE products SET brand = '2.SHARP', product_group = 'Máy giặt', product_type = '2.Máy giặt', capacity_value = 9.00 WHERE sku = 'SHAMGESFM90CBDG';
UPDATE products SET brand = '1.TOSHIBA', product_group = 'Tủ lạnh', product_type = '1.Tủ lạnh', capacity_value = 900.00 WHERE sku = 'TOSTLRF900WI';
UPDATE products SET brand = '1.TOSHIBA', product_group = 'Máy giặt', product_type = '2.Máy giặt', capacity_value = 18.00 WHERE sku = 'TOSMGDUN1800';
UPDATE products SET brand = '1.TOSHIBA', product_group = 'Máy sấy', product_type = '3.Máy sấy', capacity_value = 9.00 WHERE sku = 'TOSMSK90MEV';
UPDATE products SET brand = '3.PANASONIC', product_group = 'Tủ lạnh', product_type = '1.Tủ lạnh', capacity_value = 326.00 WHERE sku = 'PANTLTL351VGMV';
UPDATE products SET brand = 'DAIKIN', product_group = 'Điều hoà', product_type = '4.Điều hoà', capacity_value = 0.00 WHERE sku = 'DAIKDLFTKB25YVMV';
UPDATE products SET brand = 'DAIKIN', product_group = 'Điều hoà', product_type = '4.Điều hoà', capacity_value = 0.00 WHERE sku = 'DAIKDLFTHF25XVMV';
UPDATE products SET brand = '5.ELECTROLUX', product_group = 'Thiết bị gia dụng', product_type = '6.Gia dụng', capacity_value = 0.00 WHERE sku = 'LUXEDH12TRBD2';
UPDATE products SET brand = '5.ELECTROLUX', product_group = 'Máy sấy', product_type = '3.Máy sấy', capacity_value = 9.00 WHERE sku = 'ELEMSEDH903R7SC';
UPDATE products SET brand = '5.ELECTROLUX', product_group = 'Máy sấy', product_type = '3.Máy sấy', capacity_value = 9.00 WHERE sku = 'ELEMSEDH903R7WC';
UPDATE products SET brand = '3.PANASONIC', product_group = 'Máy giặt', product_type = '2.Máy giặt', capacity_value = 13.50 WHERE sku = 'PANMGNFD135X3BV';
UPDATE products SET brand = '3.PANASONIC', product_group = 'Tủ lạnh', product_type = '1.Tủ lạnh', capacity_value = 260.00 WHERE sku = 'PANTL261APSV';
UPDATE products SET brand = '3.PANASONIC', product_group = 'Tủ lạnh', product_type = '1.Tủ lạnh', capacity_value = 322.00 WHERE sku = 'PANTL361GPKV';
UPDATE products SET brand = '2.SHARP', product_group = 'Máy giặt', product_type = '2.Máy giặt', capacity_value = 10.50 WHERE sku = 'SHAMGESTM105CS';
UPDATE products SET brand = '5.ELECTROLUX', product_group = 'Máy sấy', product_type = '3.Máy sấy', capacity_value = 9.00 WHERE sku = 'ELEMSEDH902R9SC';
UPDATE products SET brand = '1.TOSHIBA', product_group = 'Máy giặt', product_type = '2.Máy giặt', capacity_value = 16.00 WHERE sku = 'TOSMGDM1600LV(SG)';
UPDATE products SET brand = 'DAIKIN', product_group = 'Điều hoà', product_type = '4.Điều hoà', capacity_value = 0.00 WHERE sku = 'DAIKDLFTF50XV1V';
UPDATE products SET brand = '1.TOSHIBA', product_group = 'Tủ lạnh', product_type = '1.Tủ lạnh', capacity_value = 768.00 WHERE sku = 'TOSTLRS910WI';
UPDATE products SET brand = '2.SHARP', product_group = 'Máy giặt', product_type = '2.Máy giặt', capacity_value = 12.50 WHERE sku = 'SHAMGESTM125MR';
UPDATE products SET brand = '3.PANASONIC', product_group = 'Tủ lạnh', product_type = '1.Tủ lạnh', capacity_value = 170.00 WHERE sku = 'PANTLBA190PPVN';
UPDATE products SET brand = '5.ELECTROLUX', product_group = 'Thiết bị gia dụng', product_type = '6.Gia dụng', capacity_value = 0.00 WHERE sku = 'LUXEDH14TRBD2';
UPDATE products SET brand = '1.TOSHIBA', product_group = 'Tủ đông-Tủ mát', product_type = '5.Tủ đông-Tủ mát', capacity_value = 0.00 WHERE sku = 'TOSTDRC185CM';
UPDATE products SET brand = '2.SHARP', product_group = 'Tủ lạnh', product_type = '1.Tủ lạnh', capacity_value = 417.00 WHERE sku = 'SHATLSJX417WD';
UPDATE products SET brand = '2.SHARP', product_group = 'Tủ lạnh', product_type = '1.Tủ lạnh', capacity_value = 523.00 WHERE sku = 'SHATLFXP560VGBK';
UPDATE products SET brand = '4.HITACHI', product_group = 'Tủ lạnh', product_type = '1.Tủ lạnh', capacity_value = 670.00 WHERE sku = 'HITTLRGW670TVXM';
UPDATE products SET brand = '1.TOSHIBA', product_group = 'Máy sấy', product_type = '3.Máy sấy', capacity_value = 11.00 WHERE sku = 'TOSMSBP110GHV(MG)';
UPDATE products SET brand = '1.TOSHIBA', product_group = 'Tủ lạnh', product_type = '1.Tủ lạnh', capacity_value = 355.00 WHERE sku = 'TOSTLRB405WE';
UPDATE products SET brand = '2.SHARP', product_group = 'Tủ lạnh', product_type = '1.Tủ lạnh', capacity_value = 660.00 WHERE sku = 'SHATLSBXP600VG';
UPDATE products SET brand = '2.SHARP', product_group = 'Tủ lạnh', product_type = '1.Tủ lạnh', capacity_value = 610.00 WHERE sku = 'SHATLFX610VSL';
UPDATE products SET brand = '1.TOSHIBA', product_group = 'Máy giặt', product_type = '2.Máy giặt', capacity_value = 11.50 WHERE sku = 'TOSMGT25BU1150';
UPDATE products SET brand = '4.HITACHI', product_group = 'Tủ lạnh', product_type = '1.Tủ lạnh', capacity_value = 800.00 WHERE sku = 'HITLM800GVGV0G';
UPDATE products SET brand = 'SANAKY', product_group = 'Tủ đông-Tủ mát', product_type = '5.Tủ đông-Tủ mát', capacity_value = 0.00 WHERE sku = 'TDSANA3699W1';
UPDATE products SET brand = 'SANAKY', product_group = 'Tủ đông-Tủ mát', product_type = '5.Tủ đông-Tủ mát', capacity_value = 0.00 WHERE sku = 'TDSANA4099W1';
UPDATE products SET brand = '1.TOSHIBA', product_group = 'Máy giặt', product_type = '2.Máy giặt', capacity_value = 16.00 WHERE sku = 'TOSMGDUHN1600LV(MG)';
UPDATE products SET brand = '3.PANASONIC', product_group = 'Tủ lạnh', product_type = '1.Tủ lạnh', capacity_value = 381.00 WHERE sku = 'PANTL381VGMV';
UPDATE products SET brand = '5.ELECTROLUX', product_group = 'Máy giặt', product_type = '2.Máy giặt', capacity_value = 10.00 WHERE sku = 'ELEMGEWF1024D3MS';
UPDATE products SET brand = '1.TOSHIBA', product_group = 'Máy giặt', product_type = '2.Máy giặt', capacity_value = 10.50 WHERE sku = 'TOSMGTWD21BU115';
UPDATE products SET brand = 'SANAKY', product_group = 'Tủ đông-Tủ mát', product_type = '5.Tủ đông-Tủ mát', capacity_value = 0.00 WHERE sku = 'PINIMTD29WF0';
UPDATE products SET brand = '5.ELECTROLUX', product_group = 'Máy sấy', product_type = '3.Máy sấy', capacity_value = 9.00 WHERE sku = 'ELEMSEDS904N3SC';
UPDATE products SET brand = '3.PANASONIC', product_group = 'Tủ lạnh', product_type = '1.Tủ lạnh', capacity_value = 420.00 WHERE sku = 'PANTLBX471XGKV';
UPDATE products SET brand = 'DAIKIN', product_group = 'Điều hoà', product_type = '4.Điều hoà', capacity_value = 0.00 WHERE sku = 'DAIKDLFTHF50VAMV';
UPDATE products SET brand = '2.SHARP', product_group = 'Tủ lạnh', product_type = '1.Tủ lạnh', capacity_value = 605.00 WHERE sku = 'SHATLSBX530VSL';
UPDATE products SET brand = '5.ELECTROLUX', product_group = 'Thiết bị gia dụng', product_type = '6.Gia dụng', capacity_value = 0.00 WHERE sku = 'LUXEDH10TRBW1';
UPDATE products SET brand = '1.TOSHIBA', product_group = 'Máy giặt', product_type = '2.Máy giặt', capacity_value = 8.00 WHERE sku = 'TOSMGT08DU1600LV(MK)';
UPDATE products SET brand = '4.HITACHI', product_group = 'Tủ lạnh', product_type = '1.Tủ lạnh', capacity_value = 525.00 WHERE sku = 'HITTLHRSN9552DGBVN';
UPDATE products SET brand = 'SANAKY', product_group = 'Tủ đông-Tủ mát', product_type = '5.Tủ đông-Tủ mát', capacity_value = 0.00 WHERE sku = 'TDSAN2899W1';
UPDATE products SET brand = '3.PANASONIC', product_group = 'Máy giặt', product_type = '2.Máy giặt', capacity_value = 10.00 WHERE sku = 'PANMGNAS106FC';
UPDATE products SET brand = '5.ELECTROLUX', product_group = 'Máy giặt', product_type = '2.Máy giặt', capacity_value = 11.00 WHERE sku = 'ELEMGEWF1143R7SC';
UPDATE products SET brand = '2.SHARP', product_group = 'Tủ lạnh', product_type = '1.Tủ lạnh', capacity_value = 472.00 WHERE sku = 'SHATLSBX440VSL';
UPDATE products SET brand = 'SANAKY', product_group = 'Tủ đông-Tủ mát', product_type = '5.Tủ đông-Tủ mát', capacity_value = 0.00 WHERE sku = 'PINIMTD39WF0';
UPDATE products SET brand = '5.ELECTROLUX', product_group = 'Máy giặt', product_type = '2.Máy giặt', capacity_value = 10.00 WHERE sku = 'ELEMGEWF1043R7SC';
UPDATE products SET brand = '3.PANASONIC', product_group = 'Tủ lạnh', product_type = '1.Tủ lạnh', capacity_value = 592.00 WHERE sku = 'PANTLYW590YMMV';
UPDATE products SET brand = '2.SHARP', product_group = 'Tủ lạnh', product_type = '1.Tủ lạnh', capacity_value = 262.00 WHERE sku = 'SHATLX270VDG';
UPDATE products SET brand = '1.TOSHIBA', product_group = 'Máy giặt', product_type = '2.Máy giặt', capacity_value = 14.00 WHERE sku = 'TOSMGT25BZU115';
UPDATE products SET brand = '4.HITACHI', product_group = 'Tủ lạnh', product_type = '1.Tủ lạnh', capacity_value = 740.00 WHERE sku = 'HITTLRZX740KV';
UPDATE products SET brand = '1.TOSHIBA', product_group = 'Máy giặt', product_type = '2.Máy giặt', capacity_value = 11.00 WHERE sku = 'TOSMGAWDM1100PV';
UPDATE products SET brand = '3.PANASONIC', product_group = 'Tủ lạnh', product_type = '1.Tủ lạnh', capacity_value = 322.00 WHERE sku = 'PANTLBV361WGK';
UPDATE products SET brand = 'SANAKY', product_group = 'Tủ đông-Tủ mát', product_type = '5.Tủ đông-Tủ mát', capacity_value = 0.00 WHERE sku = 'PINIMTD49WF0';
UPDATE products SET brand = '3.PANASONIC', product_group = 'Tủ lạnh', product_type = '1.Tủ lạnh', capacity_value = 420.00 WHERE sku = 'PANTLBX421WGKV';
UPDATE products SET brand = '5.ELECTROLUX', product_group = 'Máy sấy', product_type = '3.Máy sấy', capacity_value = 9.00 WHERE sku = 'ELEMSEDS904H3WC';
UPDATE products SET brand = '3.PANASONIC', product_group = 'Tủ lạnh', product_type = '1.Tủ lạnh', capacity_value = 420.00 WHERE sku = 'PANTLBX471WGKV';
UPDATE products SET brand = '2.SHARP', product_group = 'Tủ lạnh', product_type = '1.Tủ lạnh', capacity_value = 330.00 WHERE sku = 'SHATLBF330VDG';
UPDATE products SET brand = '2.SHARP', product_group = 'Máy giặt', product_type = '2.Máy giặt', capacity_value = 11.00 WHERE sku = 'SHAMGESTM110CD-DS';
UPDATE products SET brand = '1.TOSHIBA', product_group = 'Tủ lạnh', product_type = '1.Tủ lạnh', capacity_value = 905.00 WHERE sku = 'TOSTLRS905WIA';
UPDATE products SET brand = '3.PANASONIC', product_group = 'Tủ lạnh', product_type = '1.Tủ lạnh', capacity_value = 420.00 WHERE sku = 'PANTLBX421XGKV';
UPDATE products SET brand = '3.PANASONIC', product_group = 'Máy sấy', product_type = '3.Máy sấy', capacity_value = 9.50 WHERE sku = 'PANMSEH95JD1BV';
UPDATE products SET brand = '2.SHARP', product_group = 'Máy giặt', product_type = '2.Máy giặt', capacity_value = 9.00 WHERE sku = 'SHAMGESFM90CBSB';
UPDATE products SET brand = 'AUFIT', product_group = 'Điều hoà', product_type = '4.Điều hoà', capacity_value = 0.00 WHERE sku = 'AFW12FHA4DI-3VN';
UPDATE products SET brand = '2.SHARP', product_group = 'Máy giặt', product_type = '2.Máy giặt', capacity_value = 11.00 WHERE sku = 'SHAMGESFM110CBDG';
UPDATE products SET brand = '5.ELECTROLUX', product_group = 'Máy giặt', product_type = '2.Máy giặt', capacity_value = 11.00 WHERE sku = 'ELEMGEWF1142R9SC';
UPDATE products SET brand = '5.ELECTROLUX', product_group = 'Máy giặt', product_type = '2.Máy giặt', capacity_value = 10.00 WHERE sku = 'ELEGSEWW1023P5SC';
UPDATE products SET brand = '3.PANASONIC', product_group = 'Tủ lạnh', product_type = '1.Tủ lạnh', capacity_value = 342.00 WHERE sku = 'PANTLTV341VGMV';
UPDATE products SET brand = '5.ELECTROLUX', product_group = 'Thiết bị gia dụng', product_type = '8.Khác', capacity_value = 0.00 WHERE sku = 'LUXEDH16TRBD3';
UPDATE products SET brand = '5.ELECTROLUX', product_group = 'Máy giặt', product_type = '2.Máy giặt', capacity_value = 13.00 WHERE sku = 'ELEMGEWF1343R7WC';
UPDATE products SET brand = '1.TOSHIBA', product_group = 'Máy sấy', product_type = '3.Máy sấy', capacity_value = 11.00 WHERE sku = 'TOSMSBK110GHV';
UPDATE products SET brand = '2.SHARP', product_group = 'Máy giặt', product_type = '2.Máy giặt', capacity_value = 13.00 WHERE sku = 'SHAMGESTM130CD-DS';
UPDATE products SET brand = 'SANAKY', product_group = 'Tủ đông-Tủ mát', product_type = '5.Tủ đông-Tủ mát', capacity_value = 0.00 WHERE sku = 'TDSANAVH4099A1';
UPDATE products SET brand = '3.PANASONIC', product_group = 'Máy giặt', product_type = '2.Máy giặt', capacity_value = 11.00 WHERE sku = 'PANMGNAD11AR1BV';
UPDATE products SET brand = '2.SHARP', product_group = 'Tủ lạnh', product_type = '1.Tủ lạnh', capacity_value = 650.00 WHERE sku = 'SHATLFX650VMK';
UPDATE products SET brand = '3.PANASONIC', product_group = 'Tủ lạnh', product_type = '1.Tủ lạnh', capacity_value = 268.00 WHERE sku = 'PANTLTV301BPKV';
UPDATE products SET brand = 'SANAKY', product_group = 'Tủ đông-Tủ mát', product_type = '5.Tủ đông-Tủ mát', capacity_value = 0.00 WHERE sku = 'TDSA8699HY3';
UPDATE products SET brand = '5.ELECTROLUX', product_group = 'Máy giặt', product_type = '2.Máy giặt', capacity_value = 10.00 WHERE sku = 'ELEMGEWF1043R7WC';
UPDATE products SET brand = '2.SHARP', product_group = 'Máy giặt', product_type = '2.Máy giặt', capacity_value = 15.00 WHERE sku = 'SHAMGESTM150CD-DS';
UPDATE products SET brand = '3.PANASONIC', product_group = 'Máy giặt', product_type = '2.Máy giặt', capacity_value = 9.50 WHERE sku = 'PANMGNFD95X1LRV';
UPDATE products SET brand = '1.TOSHIBA', product_group = 'Máy giặt', product_type = '2.Máy giặt', capacity_value = 14.00 WHERE sku = 'TOSMG25BZU115';
UPDATE products SET brand = '3.PANASONIC', product_group = 'Máy giặt', product_type = '2.Máy giặt', capacity_value = 11.50 WHERE sku = 'PANMGSV115FW1BV';
UPDATE products SET brand = 'SANAKY', product_group = 'Tủ đông-Tủ mát', product_type = '5.Tủ đông-Tủ mát', capacity_value = 0.00 WHERE sku = 'TMSAN408KL';
UPDATE products SET brand = 'AUFIT', product_group = 'Điều hoà', product_type = '4.Điều hoà', capacity_value = 0.00 WHERE sku = 'AFW18FHA4DI-5VN';
UPDATE products SET brand = '5.ELECTROLUX', product_group = 'Máy giặt', product_type = '2.Máy giặt', capacity_value = 11.00 WHERE sku = 'ELEMGEWF1143R7WC';
UPDATE products SET brand = '3.PANASONIC', product_group = 'Máy giặt', product_type = '2.Máy giặt', capacity_value = 15.00 WHERE sku = 'PANMGNAS157FW1BV';
UPDATE products SET brand = 'SANAKY', product_group = 'Tủ đông-Tủ mát', product_type = '5.Tủ đông-Tủ mát', capacity_value = 0.00 WHERE sku = 'TDSAN3699A1';
UPDATE products SET brand = '3.PANASONIC', product_group = 'Máy giặt', product_type = '2.Máy giặt', capacity_value = 10.50 WHERE sku = 'PANMGS056FR1BV';
UPDATE products SET brand = '3.PANASONIC', product_group = 'Máy giặt', product_type = '2.Máy giặt', capacity_value = 10.00 WHERE sku = 'PANMG10FC1';
UPDATE products SET brand = '5.ELECTROLUX', product_group = 'Máy giặt', product_type = '2.Máy giặt', capacity_value = 10.00 WHERE sku = 'ELEMGEWF1023P5MS';
UPDATE products SET brand = '5.ELECTROLUX', product_group = 'Tủ lạnh', product_type = '1.Tủ lạnh', capacity_value = 500.00 WHERE sku = 'ELETLEQE4960AB';
UPDATE products SET brand = 'SANAKY', product_group = 'Tủ đông-Tủ mát', product_type = '5.Tủ đông-Tủ mát', capacity_value = 0.00 WHERE sku = 'TMSANV308KL';
UPDATE products SET brand = '5.ELECTROLUX', product_group = 'Tủ lạnh', product_type = '1.Tủ lạnh', capacity_value = 343.00 WHERE sku = 'ELETLETB3440MH';
UPDATE products SET brand = 'SANAKY', product_group = 'Tủ đông-Tủ mát', product_type = '5.Tủ đông-Tủ mát', capacity_value = 0.00 WHERE sku = 'PINIMTD15AF';
UPDATE products SET brand = '5.ELECTROLUX', product_group = 'Máy giặt', product_type = '2.Máy giặt', capacity_value = 10.00 WHERE sku = 'ELEMGEWF1023P5MW';
UPDATE products SET brand = '5.ELECTROLUX', product_group = 'Máy giặt', product_type = '2.Máy giặt', capacity_value = 11.00 WHERE sku = 'ELEGSEWW1123P5WC';
UPDATE products SET brand = '5.ELECTROLUX', product_group = 'Máy sấy', product_type = '3.Máy sấy', capacity_value = 9.00 WHERE sku = 'ELEMSEDV904N3MSC';
UPDATE products SET brand = '5.ELECTROLUX', product_group = 'Máy giặt', product_type = '2.Máy giặt', capacity_value = 9.00 WHERE sku = 'ELEMGEWF9023P5MW';
UPDATE products SET brand = '5.ELECTROLUX', product_group = 'Máy sấy', product_type = '3.Máy sấy', capacity_value = 9.00 WHERE sku = 'ELEMSEDV904H3MWC';
UPDATE products SET brand = '3.PANASONIC', product_group = 'Máy giặt', product_type = '2.Máy giặt', capacity_value = 16.50 WHERE sku = 'PANMGNFD165V3BV';
UPDATE products SET brand = 'SANAKY', product_group = 'Tủ đông-Tủ mát', product_type = '5.Tủ đông-Tủ mát', capacity_value = 0.00 WHERE sku = 'TDSA6699HY3';
UPDATE products SET brand = 'SANAKY', product_group = 'Tủ đông-Tủ mát', product_type = '5.Tủ đông-Tủ mát', capacity_value = 0.00 WHERE sku = 'TDSAN3699W2KD';
UPDATE products SET brand = '5.ELECTROLUX', product_group = 'Máy giặt', product_type = '2.Máy giặt', capacity_value = 9.00 WHERE sku = 'ELEMGEWF9023P5MS';
UPDATE products SET brand = '5.ELECTROLUX', product_group = 'Máy sấy', product_type = '3.Máy sấy', capacity_value = 8.00 WHERE sku = 'ELEMSEDV804H3MWC';
UPDATE products SET brand = '5.ELECTROLUX', product_group = 'Máy giặt', product_type = '2.Máy giặt', capacity_value = 11.00 WHERE sku = 'ELEGSEWW1143R7SC';
UPDATE products SET brand = 'SANAKY', product_group = 'Tủ đông-Tủ mát', product_type = '5.Tủ đông-Tủ mát', capacity_value = 0.00 WHERE sku = 'PINIMTD39AF0';
UPDATE products SET brand = 'SANAKY', product_group = 'Tủ đông-Tủ mát', product_type = '5.Tủ đông-Tủ mát', capacity_value = 0.00 WHERE sku = 'PINIMTD49AF';
UPDATE products SET brand = 'SANAKY', product_group = 'Tủ đông-Tủ mát', product_type = '5.Tủ đông-Tủ mát', capacity_value = 0.00 WHERE sku = 'TDSANA4099W2KD';
UPDATE products SET brand = '4.HITACHI', product_group = 'Tủ lạnh', product_type = '1.Tủ lạnh', capacity_value = 540.00 WHERE sku = 'HITLHW540RVX';
UPDATE products SET brand = 'SANAKY', product_group = 'Tủ đông-Tủ mát', product_type = '5.Tủ đông-Tủ mát', capacity_value = 0.00 WHERE sku = 'TMSNK358KL';
UPDATE products SET brand = '5.ELECTROLUX', product_group = 'Máy giặt', product_type = '2.Máy giặt', capacity_value = 10.00 WHERE sku = 'ELEGSEWW1343R7WC';
UPDATE products SET brand = '5.ELECTROLUX', product_group = 'Tủ lạnh', product_type = '1.Tủ lạnh', capacity_value = 563.00 WHERE sku = 'ELETLEQE5660AB';
UPDATE products SET brand = '5.ELECTROLUX', product_group = 'Máy giặt', product_type = '2.Máy giặt', capacity_value = 13.00 WHERE sku = 'ELEMGEWF1343P5WC';
UPDATE products SET brand = 'SANAKY', product_group = 'Tủ đông-Tủ mát', product_type = '5.Tủ đông-Tủ mát', capacity_value = 0.00 WHERE sku = 'PINITDSAN29AF0';
UPDATE products SET brand = '5.ELECTROLUX', product_group = 'Máy giặt', product_type = '2.Máy giặt', capacity_value = 10.00 WHERE sku = 'ELEMGEWW1343P5MSC';
UPDATE products SET brand = 'SANAKY', product_group = 'Tủ đông-Tủ mát', product_type = '5.Tủ đông-Tủ mát', capacity_value = 0.00 WHERE sku = 'TDSANVH6699W1';
UPDATE products SET brand = '5.ELECTROLUX', product_group = 'Tủ lạnh', product_type = '1.Tủ lạnh', capacity_value = 300.00 WHERE sku = 'ELETLETM3100MLB';
UPDATE products SET brand = 'SANAKY', product_group = 'Tủ đông-Tủ mát', product_type = '5.Tủ đông-Tủ mát', capacity_value = 0.00 WHERE sku = 'TMSAN258KL';
UPDATE products SET brand = 'SANAKY', product_group = 'Tủ đông-Tủ mát', product_type = '5.Tủ đông-Tủ mát', capacity_value = 0.00 WHERE sku = 'TDSANA2899A1';
UPDATE products SET brand = '5.ELECTROLUX', product_group = 'Máy giặt', product_type = '2.Máy giặt', capacity_value = 13.00 WHERE sku = 'ELEMGEWF1342R9SC';
UPDATE products SET brand = '5.ELECTROLUX', product_group = 'Tủ lạnh', product_type = '1.Tủ lạnh', capacity_value = 344.00 WHERE sku = 'ELETLETM3440MLB';
UPDATE products SET brand = 'AUFIT', product_group = 'Điều hoà', product_type = '4.Điều hoà', capacity_value = 0.00 WHERE sku = 'AFW24FHA4DI-3VN';
UPDATE products SET brand = '3.PANASONIC', product_group = 'Máy sấy', product_type = '3.Máy sấy', capacity_value = 10.50 WHERE sku = 'PANMSEH05JD1V';
UPDATE products SET brand = '5.ELECTROLUX', product_group = 'Tủ lạnh', product_type = '1.Tủ lạnh', capacity_value = 360.00 WHERE sku = 'ELETLEBB3742MH';
UPDATE products SET brand = '3.PANASONIC', product_group = 'Tủ lạnh', product_type = '1.Tủ lạnh', capacity_value = 188.00 WHERE sku = 'PANTLBA229PAVN';
UPDATE products SET brand = '3.PANASONIC', product_group = 'Tủ lạnh', product_type = '1.Tủ lạnh', capacity_value = 650.00 WHERE sku = 'PANTLWY720ZMMV';
UPDATE products SET brand = '4.HITACHI', product_group = 'Tủ lạnh', product_type = '1.Tủ lạnh', capacity_value = 615.00 WHERE sku = 'HITLRHW620XRV';
UPDATE products SET brand = '1.TOSHIBA', product_group = 'Tủ lạnh', product_type = '1.Tủ lạnh', capacity_value = 690.00 WHERE sku = 'TOSTLRF690WI-PGV(67)';
UPDATE products SET brand = '4.HITACHI', product_group = 'Tủ lạnh', product_type = '1.Tủ lạnh', capacity_value = 615.00 WHERE sku = 'HITLRHW620RVXK';
UPDATE products SET brand = 'SANAKY', product_group = 'Tủ đông-Tủ mát', product_type = '5.Tủ đông-Tủ mát', capacity_value = 0.00 WHERE sku = 'TDSANVH5699W1';
UPDATE products SET brand = '3.PANASONIC', product_group = 'Tủ lạnh', product_type = '1.Tủ lạnh', capacity_value = 281.00 WHERE sku = 'PANTLBV281BGMV';
UPDATE products SET brand = '1.TOSHIBA', product_group = 'Tủ lạnh', product_type = '1.Tủ lạnh', capacity_value = 562.00 WHERE sku = 'TOSTLRF695WI-PGV(67)';
UPDATE products SET brand = '5.ELECTROLUX', product_group = 'Máy giặt', product_type = '2.Máy giặt', capacity_value = 13.00 WHERE sku = 'ELEMGEWF1342R9MSC';
UPDATE products SET brand = 'SANAKY', product_group = 'Tủ đông-Tủ mát', product_type = '5.Tủ đông-Tủ mát', capacity_value = 0.00 WHERE sku = 'TDSANVH5699HY';
UPDATE products SET brand = '5.ELECTROLUX', product_group = 'Máy giặt', product_type = '2.Máy giặt', capacity_value = 10.00 WHERE sku = 'ELEMGEWF1043R7MS';
UPDATE products SET brand = '5.ELECTROLUX', product_group = 'Tủ lạnh', product_type = '1.Tủ lạnh', capacity_value = 346.00 WHERE sku = 'ELETLETB3460MLB';
UPDATE products SET brand = '5.ELECTROLUX', product_group = 'Máy giặt', product_type = '2.Máy giặt', capacity_value = 10.00 WHERE sku = 'ELEMGEWW1343R7MW';
UPDATE products SET brand = '2.SHARP', product_group = 'Tủ lạnh', product_type = '1.Tủ lạnh', capacity_value = 700.00 WHERE sku = 'SHATLFXPI700VGBK';
UPDATE products SET brand = '5.ELECTROLUX', product_group = 'Máy giặt', product_type = '2.Máy giặt', capacity_value = 10.00 WHERE sku = 'ELEMGEWF1043R7MW';
UPDATE products SET brand = '5.ELECTROLUX', product_group = 'Máy giặt', product_type = '2.Máy giặt', capacity_value = 11.00 WHERE sku = 'ELEGSEWW1143R7MS';
UPDATE products SET brand = '5.ELECTROLUX', product_group = 'Máy giặt', product_type = '2.Máy giặt', capacity_value = 13.00 WHERE sku = 'ELEMGEWF1343P5MWC';
UPDATE products SET brand = '5.ELECTROLUX', product_group = 'Máy giặt', product_type = '2.Máy giặt', capacity_value = 11.00 WHERE sku = 'ELEMGEWF1143R7MS';
UPDATE products SET brand = '5.ELECTROLUX', product_group = 'Máy giặt', product_type = '2.Máy giặt', capacity_value = 9.00 WHERE sku = 'ELEGSEWW9024P3WC';
UPDATE products SET brand = '5.ELECTROLUX', product_group = 'Máy giặt', product_type = '2.Máy giặt', capacity_value = 11.00 WHERE sku = 'ELEMGEWF1143R7MW';
UPDATE products SET brand = '5.ELECTROLUX', product_group = 'Tủ lạnh', product_type = '1.Tủ lạnh', capacity_value = 376.00 WHERE sku = 'ELETLETB3760MH';
UPDATE products SET brand = '5.ELECTROLUX', product_group = 'Máy giặt', product_type = '2.Máy giặt', capacity_value = 13.00 WHERE sku = 'ELEMGEWF1343R7MW';
UPDATE products SET brand = '5.ELECTROLUX', product_group = 'Tủ lạnh', product_type = '1.Tủ lạnh', capacity_value = 374.00 WHERE sku = 'ELETLETB3740MH';
UPDATE products SET brand = '5.ELECTROLUX', product_group = 'Máy giặt', product_type = '2.Máy giặt', capacity_value = 11.00 WHERE sku = 'ELEGSEWW1123P5MW';
UPDATE products SET brand = '5.ELECTROLUX', product_group = 'Tủ lạnh', product_type = '1.Tủ lạnh', capacity_value = 344.00 WHERE sku = 'ETM3440L-B';
UPDATE products SET brand = 'SANAKY', product_group = 'Tủ đông-Tủ mát', product_type = '5.Tủ đông-Tủ mát', capacity_value = 0.00 WHERE sku = 'TDSANA5699HY3';
UPDATE products SET brand = 'SANAKY', product_group = 'Tủ đông-Tủ mát', product_type = '5.Tủ đông-Tủ mát', capacity_value = 0.00 WHERE sku = 'PINIMTD59WF';
UPDATE products SET brand = '5.ELECTROLUX', product_group = 'Máy giặt', product_type = '2.Máy giặt', capacity_value = 11.00 WHERE sku = 'ELEMGEWF1142R9MS';
UPDATE products SET brand = '5.ELECTROLUX', product_group = 'Máy sấy', product_type = '3.Máy sấy', capacity_value = 9.00 WHERE sku = 'ELEMSEDS904N3MSC';
UPDATE products SET brand = '5.ELECTROLUX', product_group = 'Máy giặt', product_type = '2.Máy giặt', capacity_value = 10.00 WHERE sku = 'ELEGSEWW1023P5MS';
UPDATE products SET brand = '3.PANASONIC', product_group = 'Máy giặt', product_type = '2.Máy giặt', capacity_value = 9.00 WHERE sku = 'PANMGNA90FC1LVT';
UPDATE products SET brand = '5.ELECTROLUX', product_group = 'Máy sấy', product_type = '3.Máy sấy', capacity_value = 9.00 WHERE sku = 'ELEMSEDS904H3MWC';
UPDATE products SET brand = '5.ELECTROLUX', product_group = 'Tủ lạnh', product_type = '1.Tủ lạnh', capacity_value = 93.00 WHERE sku = 'ELETLEUM0930BDVN';
UPDATE products SET brand = '3.PANASONIC', product_group = 'Máy sấy', product_type = '3.Máy sấy', capacity_value = 10.50 WHERE sku = 'PANMGNHXV21X1AVT';
UPDATE products SET brand = '5.ELECTROLUX', product_group = 'Máy giặt', product_type = '2.Máy giặt', capacity_value = 9.00 WHERE sku = 'ELEGSEWW9024P3MW';
UPDATE products SET brand = '3.PANASONIC', product_group = 'Máy sấy', product_type = '6.Gia dụng', capacity_value = NULL WHERE sku = 'PANCSHCC-R340ARXV';
UPDATE products SET brand = '3.PANASONIC', product_group = 'Máy giặt', product_type = '2.Máy giặt', capacity_value = 10.00 WHERE sku = 'PANMGNFD10VR1BV';
UPDATE products SET brand = '1.TOSHIBA', product_group = 'Máy giặt', product_type = '2.Máy giặt', capacity_value = 11.50 WHERE sku = 'TOSMGT37BZP115MWV(WT)';
UPDATE products SET brand = '1.TOSHIBA', product_group = 'Máy sấy', product_type = '3.Máy sấy', capacity_value = 9.00 WHERE sku = 'TOSMST37BS90HWV(WT)';
UPDATE products SET brand = '4.HITACHI', product_group = 'Tủ lạnh', product_type = '1.Tủ lạnh', capacity_value = 540.00 WHERE sku = 'HITLRHW540RVXK';
UPDATE products SET brand = '5.ELECTROLUX', product_group = 'Tủ lạnh', product_type = '1.Tủ lạnh', capacity_value = 310.00 WHERE sku = 'ETM3100L-B';
UPDATE products SET brand = 'SANAKY', product_group = 'Tủ đông-Tủ mát', product_type = '5.Tủ đông-Tủ mát', capacity_value = 0.00 WHERE sku = 'PINIMTD69WF';
UPDATE products SET brand = 'SANAKY', product_group = 'Tủ đông-Tủ mát', product_type = '5.Tủ đông-Tủ mát', capacity_value = 0.00 WHERE sku = 'PINIMTD89AF';
UPDATE products SET brand = 'SANAKY', product_group = 'Tủ đông-Tủ mát', product_type = '5.Tủ đông-Tủ mát', capacity_value = 0.00 WHERE sku = 'TDSAN3899K';
UPDATE products SET brand = '3.PANASONIC', product_group = 'Máy giặt', product_type = '2.Máy giặt', capacity_value = 10.50 WHERE sku = 'PANMGNAV105FR1BV';
UPDATE products SET brand = 'SANAKY', product_group = 'Tủ đông-Tủ mát', product_type = '5.Tủ đông-Tủ mát', capacity_value = 0.00 WHERE sku = 'TDSANH1199HY';
UPDATE products SET brand = '3.PANASONIC', product_group = 'Máy giặt', product_type = '2.Máy giặt', capacity_value = 26.00 WHERE sku = 'PANMG26CVX1AVT';
UPDATE products SET brand = '5.ELECTROLUX', product_group = NULL, product_type = '2.Máy giặt', capacity_value = NULL WHERE sku = 'ELEMGEWW1343P5SC';
UPDATE products SET brand = 'SANAKY', product_group = 'Tủ đông-Tủ mát', product_type = '5.Tủ đông-Tủ mát', capacity_value = 0.00 WHERE sku = 'TDSAN3699A2KD';
UPDATE products SET brand = 'SANAKY', product_group = 'Tủ đông-Tủ mát', product_type = '5.Tủ đông-Tủ mát', capacity_value = 0.00 WHERE sku = 'TDSAN1599H';
UPDATE products SET brand = '5.ELECTROLUX', product_group = NULL, product_type = '1.Tủ lạnh', capacity_value = NULL WHERE sku = 'ELETLEQE4900AA';
UPDATE products SET brand = '5.ELECTROLUX', product_group = 'Tủ lạnh', product_type = '1.Tủ lạnh', capacity_value = 93.00 WHERE sku = 'ELETLEUM0930ADVN';
UPDATE products SET brand = 'SANAKY', product_group = 'Tủ đông-Tủ mát', product_type = '5.Tủ đông-Tủ mát', capacity_value = 0.00 WHERE sku = 'TDSANAK888KA';
UPDATE products SET brand = '3.PANASONIC', product_group = 'Máy giặt', product_type = '2.Máy giặt', capacity_value = 11.50 WHERE sku = 'PANMGNAFD115V3BV';
UPDATE products SET brand = 'SANAKY', product_group = 'Tủ đông-Tủ mát', product_type = '5.Tủ đông-Tủ mát', capacity_value = 0.00 WHERE sku = 'TDSAN8699HY';
UPDATE products SET brand = 'SANAKY', product_group = 'Tủ đông-Tủ mát', product_type = '5.Tủ đông-Tủ mát', capacity_value = 0.00 WHERE sku = 'TDSANV1399HY3';
UPDATE products SET brand = 'SANAKY', product_group = 'Tủ đông-Tủ mát', product_type = '5.Tủ đông-Tủ mát', capacity_value = 0.00 WHERE sku = 'TDSANA4099W3';
UPDATE products SET brand = 'SANAKY', product_group = 'Tủ đông-Tủ mát', product_type = '5.Tủ đông-Tủ mát', capacity_value = 0.00 WHERE sku = 'TDSAN4899K';
UPDATE products SET brand = 'SANAKY', product_group = 'Tủ đông-Tủ mát', product_type = '5.Tủ đông-Tủ mát', capacity_value = 0.00 WHERE sku = 'TDSANAKY8009HP';
UPDATE products SET brand = '3.PANASONIC', product_group = 'Tủ lạnh', product_type = '1.Tủ lạnh', capacity_value = 621.00 WHERE sku = 'PANTLXY680YMMV';
UPDATE products SET brand = 'SANAKY', product_group = 'Tủ đông-Tủ mát', product_type = '5.Tủ đông-Tủ mát', capacity_value = 0.00 WHERE sku = 'TMSANVH6009HP';
UPDATE products SET brand = '3.PANASONIC', product_group = 'Tủ lạnh', product_type = '1.Tủ lạnh', capacity_value = 268.00 WHERE sku = 'PANTLTV301VGMV';
UPDATE products SET brand = 'SANAKY', product_group = 'Tủ đông-Tủ mát', product_type = '5.Tủ đông-Tủ mát', capacity_value = 0.00 WHERE sku = 'TDSANVH6699W3';
UPDATE products SET brand = 'DAIKIN', product_group = NULL, product_type = '4.Điều hoà', capacity_value = NULL WHERE sku = 'RXYMQ6BVM';
UPDATE products SET brand = 'SANAKY', product_group = 'Tủ đông-Tủ mát', product_type = '5.Tủ đông-Tủ mát', capacity_value = 0.00 WHERE sku = 'TDSANA1099KA';
UPDATE products SET brand = 'SANAKY', product_group = 'Tủ đông-Tủ mát', product_type = '5.Tủ đông-Tủ mát', capacity_value = 0.00 WHERE sku = 'TMSANV1209HP3';
UPDATE products SET brand = 'SANAKY', product_group = 'Tủ đông-Tủ mát', product_type = '5.Tủ đông-Tủ mát', capacity_value = 0.00 WHERE sku = 'TDSANA4099A2KD';
UPDATE products SET brand = 'SANAKY', product_group = 'Tủ đông-Tủ mát', product_type = '5.Tủ đông-Tủ mát', capacity_value = 0.00 WHERE sku = 'PINIMTD59AF';
UPDATE products SET brand = 'SANAKY', product_group = 'Tủ đông-Tủ mát', product_type = '5.Tủ đông-Tủ mát', capacity_value = 0.00 WHERE sku = 'TDSANAKY230VD';
UPDATE products SET brand = 'SANAKY', product_group = 'Tủ đông-Tủ mát', product_type = '5.Tủ đông-Tủ mát', capacity_value = 0.00 WHERE sku = 'PINITD48KF';
UPDATE products SET brand = 'SANAKY', product_group = 'Tủ đông-Tủ mát', product_type = '5.Tủ đông-Tủ mát', capacity_value = 0.00 WHERE sku = 'PINIM69WF3';
UPDATE products SET brand = 'SANAKY', product_group = 'Tủ đông-Tủ mát', product_type = '5.Tủ đông-Tủ mát', capacity_value = 0.00 WHERE sku = 'PINIMTD49WF3';
UPDATE products SET brand = 'SANAKY', product_group = NULL, product_type = '5.Tủ đông-Tủ mát', capacity_value = NULL WHERE sku = 'TDSAN2399HY3';
UPDATE products SET brand = 'SANAKY', product_group = 'Tủ đông-Tủ mát', product_type = '5.Tủ đông-Tủ mát', capacity_value = 0.00 WHERE sku = 'TDSANA1099K3A';
UPDATE products SET brand = 'SANAKY', product_group = 'Tủ đông-Tủ mát', product_type = '5.Tủ đông-Tủ mát', capacity_value = 0.00 WHERE sku = 'TDSANVH5699W3';
UPDATE products SET brand = 'SANAKY', product_group = 'Tủ đông-Tủ mát', product_type = '5.Tủ đông-Tủ mát', capacity_value = 0.00 WHERE sku = 'TDSANA2899W2KD';
UPDATE products SET brand = 'SANAKY', product_group = 'Tủ đông-Tủ mát', product_type = '5.Tủ đông-Tủ mát', capacity_value = 0.00 WHERE sku = 'PINIM49AF3';
UPDATE products SET brand = '4.HITACHI', product_group = 'Tủ lạnh', product_type = '1.Tủ lạnh', capacity_value = 640.00 WHERE sku = 'HITLRWB640VGV0X';
UPDATE products SET brand = '3.PANASONIC', product_group = 'Máy giặt', product_type = '2.Máy giặt', capacity_value = 12.50 WHERE sku = 'PANMGFD125V1BV';
UPDATE products SET brand = 'DAIKIN', product_group = NULL, product_type = '4.Điều hoà', capacity_value = NULL WHERE sku = 'FBA60BVMA9';
UPDATE products SET brand = 'SANAKY', product_group = 'Tủ đông-Tủ mát', product_type = '5.Tủ đông-Tủ mát', capacity_value = 0.00 WHERE sku = 'TDSANVH1199HY';
UPDATE products SET brand = 'SANAKY', product_group = 'Tủ đông-Tủ mát', product_type = '5.Tủ đông-Tủ mát', capacity_value = 0.00 WHERE sku = 'TDSNK4099W4K';
UPDATE products SET brand = 'SANAKY', product_group = 'Tủ đông-Tủ mát', product_type = '5.Tủ đông-Tủ mát', capacity_value = 0.00 WHERE sku = 'TMSAN219KL';
UPDATE products SET brand = 'SANAKY', product_group = 'Tủ đông-Tủ mát', product_type = '5.Tủ đông-Tủ mát', capacity_value = 0.00 WHERE sku = 'TMSAN1520HP';
UPDATE products SET brand = 'SANAKY', product_group = 'Tủ đông-Tủ mát', product_type = '5.Tủ đông-Tủ mát', capacity_value = 0.00 WHERE sku = 'PINIMTM408KL';
UPDATE products SET brand = 'SANAKY', product_group = 'Tủ đông-Tủ mát', product_type = '5.Tủ đông-Tủ mát', capacity_value = 0.00 WHERE sku = 'TMSANV308WL';
UPDATE products SET brand = 'SANAKY', product_group = 'Tủ đông-Tủ mát', product_type = '5.Tủ đông-Tủ mát', capacity_value = 0.00 WHERE sku = 'TMSANVH1520HP';
UPDATE products SET brand = 'SANAKY', product_group = 'Tủ đông-Tủ mát', product_type = '5.Tủ đông-Tủ mát', capacity_value = 0.00 WHERE sku = 'TDSNK8699HY4K';
UPDATE products SET brand = 'SANAKY', product_group = 'Tủ đông-Tủ mát', product_type = '5.Tủ đông-Tủ mát', capacity_value = 0.00 WHERE sku = 'TMSNK408K3L';
UPDATE products SET brand = '3.PANASONIC', product_group = 'Tủ lạnh', product_type = '1.Tủ lạnh', capacity_value = 300.00 WHERE sku = 'PANTLBV331WGKV';
UPDATE products SET brand = 'SANAKY', product_group = 'Tủ đông-Tủ mát', product_type = '5.Tủ đông-Tủ mát', capacity_value = 0.00 WHERE sku = 'TDSANA4099A4K';
UPDATE products SET brand = 'SANAKY', product_group = 'Tủ đông-Tủ mát', product_type = '5.Tủ đông-Tủ mát', capacity_value = 0.00 WHERE sku = 'TDSANAKY4899KB';
UPDATE products SET brand = 'SANAKY', product_group = 'Tủ đông-Tủ mát', product_type = '5.Tủ đông-Tủ mát', capacity_value = 0.00 WHERE sku = 'TDSANAVH4099A3';
UPDATE products SET brand = 'SANAKY', product_group = 'Tủ đông-Tủ mát', product_type = '5.Tủ đông-Tủ mát', capacity_value = 0.00 WHERE sku = 'TDSAN3699A3';
UPDATE products SET brand = 'SANAKY', product_group = 'Tủ đông-Tủ mát', product_type = '5.Tủ đông-Tủ mát', capacity_value = 0.00 WHERE sku = 'PINITD89AF3';
UPDATE products SET brand = '3.PANASONIC', product_group = 'Máy giặt', product_type = '2.Máy giặt', capacity_value = 12.50 WHERE sku = 'PANMGNAFD125V4BV';
UPDATE products SET brand = 'SANAKY', product_group = 'Tủ đông-Tủ mát', product_type = '5.Tủ đông-Tủ mát', capacity_value = 0.00 WHERE sku = 'PINIMTD49W2';
UPDATE products SET brand = 'SANAKY', product_group = 'Tủ đông-Tủ mát', product_type = '5.Tủ đông-Tủ mát', capacity_value = 0.00 WHERE sku = 'TMSNKVH5089K3';
UPDATE products SET brand = 'SANAKY', product_group = 'Tủ đông-Tủ mát', product_type = '5.Tủ đông-Tủ mát', capacity_value = 0.00 WHERE sku = 'PINIM69AF3';
UPDATE products SET brand = 'SANAKY', product_group = 'Tủ đông-Tủ mát', product_type = '5.Tủ đông-Tủ mát', capacity_value = 0.00 WHERE sku = 'TDSANAKYVH8009HP';
UPDATE products SET brand = 'DAIKIN', product_group = 'Điều hoà', product_type = '4.Điều hoà', capacity_value = 0.00 WHERE sku = 'DAIKDLFTKY50WVMV';
UPDATE products SET brand = '3.PANASONIC', product_group = 'Máy giặt', product_type = '2.Máy giặt', capacity_value = 10.50 WHERE sku = 'PANMGNAFD105V3BV';
UPDATE products SET brand = 'SANAKY', product_group = 'Tủ đông-Tủ mát', product_type = '5.Tủ đông-Tủ mát', capacity_value = 0.00 WHERE sku = 'TDSAN3699W3';
UPDATE products SET brand = 'SANAKY', product_group = 'Tủ đông-Tủ mát', product_type = '5.Tủ đông-Tủ mát', capacity_value = 0.00 WHERE sku = 'TDSANVH1199HYK';
UPDATE products SET brand = '3.PANASONIC', product_group = 'Tủ lạnh', product_type = '1.Tủ lạnh', capacity_value = 255.00 WHERE sku = 'PANTLBV281BVKV';
UPDATE products SET brand = 'SANAKY', product_group = 'Tủ đông-Tủ mát', product_type = '5.Tủ đông-Tủ mát', capacity_value = 0.00 WHERE sku = 'TMSAN408WL';
UPDATE products SET brand = '4.HITACHI', product_group = 'Máy giặt', product_type = '2.Máy giặt', capacity_value = 10.00 WHERE sku = 'HIMGBD100GVWH';
UPDATE products SET brand = 'SANAKY', product_group = 'Tủ đông-Tủ mát', product_type = '5.Tủ đông-Tủ mát', capacity_value = 0.00 WHERE sku = 'TMSAN358K3L';
UPDATE products SET brand = 'DAIKIN', product_group = NULL, product_type = '4.Điều hoà', capacity_value = NULL WHERE sku = 'FXSQ80PAVE9';
UPDATE products SET brand = 'SANAKY', product_group = 'Tủ đông-Tủ mát', product_type = '5.Tủ đông-Tủ mát', capacity_value = 0.00 WHERE sku = 'TDSAN2899W3';
UPDATE products SET brand = 'SANAKY', product_group = 'Tủ đông-Tủ mát', product_type = '5.Tủ đông-Tủ mát', capacity_value = 0.00 WHERE sku = 'PINIMTD29WF3';
UPDATE products SET brand = 'SANAKY', product_group = 'Tủ đông-Tủ mát', product_type = '5.Tủ đông-Tủ mát', capacity_value = 0.00 WHERE sku = 'PINIMTM4098K';
UPDATE products SET brand = 'SANAKY', product_group = 'Tủ đông-Tủ mát', product_type = '5.Tủ đông-Tủ mát', capacity_value = 0.00 WHERE sku = 'TDSANAVH2599W2KD';
UPDATE products SET brand = 'DAIKIN', product_group = NULL, product_type = '4.Điều hoà', capacity_value = NULL WHERE sku = 'FXSQ63PAVE9';
UPDATE products SET brand = '3.PANASONIC', product_group = 'Máy giặt', product_type = '2.Máy giặt', capacity_value = 16.00 WHERE sku = 'PANMGFD16V1';
UPDATE products SET brand = '5.ELECTROLUX', product_group = 'Tủ lạnh', product_type = '1.Tủ lạnh', capacity_value = 50.00 WHERE sku = 'ELETLEUM0500ADVN';
UPDATE products SET brand = 'SANAKY', product_group = 'Tủ đông-Tủ mát', product_type = '5.Tủ đông-Tủ mát', capacity_value = 0.00 WHERE sku = 'TDSAN8699HYK';
UPDATE products SET brand = 'SANAKY', product_group = 'Tủ đông-Tủ mát', product_type = '5.Tủ đông-Tủ mát', capacity_value = 0.00 WHERE sku = 'PINITD38KF';
UPDATE products SET brand = 'SANAKY', product_group = 'Thiết bị gia dụng', product_type = '6.Gia dụng', capacity_value = 0.00 WHERE sku = 'SNKCNSNK2317BB';
UPDATE products SET brand = 'SANAKY', product_group = 'Tủ đông-Tủ mát', product_type = '5.Tủ đông-Tủ mát', capacity_value = 0.00 WHERE sku = 'TDSAN3699W4K';
UPDATE products SET brand = '5.ELECTROLUX', product_group = 'Thiết bị gia dụng', product_type = '6.Gia dụng', capacity_value = 0.00 WHERE sku = 'ELECESA47200SW';
UPDATE products SET brand = 'SANAKY', product_group = 'Tủ đông-Tủ mát', product_type = '5.Tủ đông-Tủ mát', capacity_value = 0.00 WHERE sku = 'TDSANA6699W4K';
UPDATE products SET brand = 'SANAKY', product_group = 'Tủ đông-Tủ mát', product_type = '5.Tủ đông-Tủ mát', capacity_value = 0.00 WHERE sku = 'PINIMTD39WF3';
UPDATE products SET brand = 'SANAKY', product_group = 'Tủ đông-Tủ mát', product_type = '5.Tủ đông-Tủ mát', capacity_value = 0.00 WHERE sku = 'PINIMTD39AF3';
UPDATE products SET brand = '5.ELECTROLUX', product_group = NULL, product_type = '2.Máy giặt', capacity_value = NULL WHERE sku = 'ELEMGEEWF1142Q7';
UPDATE products SET brand = 'SANAKY', product_group = 'Tủ đông-Tủ mát', product_type = '5.Tủ đông-Tủ mát', capacity_value = 0.00 WHERE sku = 'TDSANA6699W2K';
UPDATE products SET brand = '4.HITACHI', product_group = 'Thiết bị gia dụng', product_type = '6.Gia dụng', capacity_value = 0.00 WHERE sku = 'HITAQD6RCWM';
UPDATE products SET brand = 'SANAKY', product_group = NULL, product_type = '6.Gia dụng', capacity_value = NULL WHERE sku = 'SNKNCVH60AM1';
UPDATE products SET brand = 'SANAKY', product_group = 'Tủ đông-Tủ mát', product_type = '5.Tủ đông-Tủ mát', capacity_value = 0.00 WHERE sku = 'PINIMTD39W2D';
UPDATE products SET brand = '3.PANASONIC', product_group = NULL, product_type = '6.Gia dụng', capacity_value = NULL WHERE sku = 'PANALKP15EHA';
UPDATE products SET brand = 'SANAKY', product_group = 'Tủ đông-Tủ mát', product_type = '5.Tủ đông-Tủ mát', capacity_value = 0.00 WHERE sku = 'TDSAN5699HY4K';
UPDATE products SET brand = 'SANAKY', product_group = 'Tủ đông-Tủ mát', product_type = '5.Tủ đông-Tủ mát', capacity_value = 0.00 WHERE sku = 'TDSANVH5699W4K';
UPDATE products SET brand = 'SANAKY', product_group = 'Tủ đông-Tủ mát', product_type = '5.Tủ đông-Tủ mát', capacity_value = 0.00 WHERE sku = 'TDSANVH4899K3B';
UPDATE products SET brand = 'SANAKY', product_group = 'Tủ đông-Tủ mát', product_type = '5.Tủ đông-Tủ mát', capacity_value = 0.00 WHERE sku = 'TDSANAKY3899K3B';
UPDATE products SET brand = 'SANAKY', product_group = 'Tủ đông-Tủ mát', product_type = '5.Tủ đông-Tủ mát', capacity_value = 0.00 WHERE sku = 'TM.VH358WL';
UPDATE products SET brand = 'SANAKY', product_group = 'Tủ đông-Tủ mát', product_type = '5.Tủ đông-Tủ mát', capacity_value = 0.00 WHERE sku = 'TDSANVH1599HYK';
UPDATE products SET brand = '5.ELECTROLUX', product_group = 'Máy sấy', product_type = '3.Máy sấy', capacity_value = 8.50 WHERE sku = 'ELEMGEDS854J3WB';
UPDATE products SET brand = 'SANAKY', product_group = 'Tủ đông-Tủ mát', product_type = '5.Tủ đông-Tủ mát', capacity_value = 0.00 WHERE sku = 'TDSANAKY3899KB';
UPDATE products SET brand = 'SANAKY', product_group = 'Tủ đông-Tủ mát', product_type = '5.Tủ đông-Tủ mát', capacity_value = 0.00 WHERE sku = 'TMSANV258K3L';
UPDATE products SET brand = '5.ELECTROLUX', product_group = 'Máy giặt', product_type = '2.Máy giặt', capacity_value = 10.00 WHERE sku = 'ELECMGEWF1024M3T';
UPDATE products SET brand = '5.ELECTROLUX', product_group = NULL, product_type = '3.Máy sấy', capacity_value = NULL WHERE sku = 'ELEMGEDV854J';
UPDATE products SET brand = 'SANAKY', product_group = 'Tủ đông-Tủ mát', product_type = '5.Tủ đông-Tủ mát', capacity_value = 0.00 WHERE sku = 'PINIMTM3598K';
UPDATE products SET brand = 'SANAKY', product_group = 'Tủ đông-Tủ mát', product_type = '5.Tủ đông-Tủ mát', capacity_value = 0.00 WHERE sku = 'TDSANAKY230VD3';
UPDATE products SET brand = '5.ELECTROLUX', product_group = 'Máy giặt', product_type = '2.Máy giặt', capacity_value = 10.00 WHERE sku = 'ELECMGEWF1024D3T';
UPDATE products SET brand = 'SANAKY', product_group = NULL, product_type = '5.Tủ đông-Tủ mát', capacity_value = NULL WHERE sku = 'TMSANVH218WL';
UPDATE products SET brand = 'SANAKY', product_group = 'Tủ đông-Tủ mát', product_type = '5.Tủ đông-Tủ mát', capacity_value = 0.00 WHERE sku = 'PINIMTD49W4KD';
UPDATE products SET brand = '5.ELECTROLUX', product_group = NULL, product_type = '3.Máy sấy', capacity_value = NULL WHERE sku = 'ELEMGEDV754H3WB';
UPDATE products SET brand = 'SANAKY', product_group = 'Tủ đông-Tủ mát', product_type = '5.Tủ đông-Tủ mát', capacity_value = 0.00 WHERE sku = 'TDSAN2899A3';
UPDATE products SET brand = 'AUFIT', product_group = 'Điều hoà', product_type = '4.Điều hoà', capacity_value = 0.00 WHERE sku = 'AF09FHA4DI-3VN';
UPDATE products SET brand = '2.SHARP', product_group = 'Máy giặt', product_type = '2.Máy giặt', capacity_value = 8.50 WHERE sku = 'SHAMGESFK852EV';
UPDATE products SET brand = 'DAIKIN', product_group = NULL, product_type = '7.Phụ kiện', capacity_value = NULL WHERE sku = 'BRC4C65';
UPDATE products SET brand = '2.SHARP', product_group = 'Máy giặt', product_type = '2.Máy giặt', capacity_value = 8.00 WHERE sku = 'SHAMGSW80GVH';
UPDATE products SET brand = 'SANAKY', product_group = NULL, product_type = '6.Gia dụng', capacity_value = NULL WHERE sku = 'SNKNCVH60WM1';
UPDATE products SET brand = 'DAIKIN', product_group = NULL, product_type = '8.Khác', capacity_value = NULL WHERE sku = 'DAIKIN01';
UPDATE products SET brand = 'DAIKIN', product_group = NULL, product_type = '8.Khác', capacity_value = NULL WHERE sku = 'DAIKIN02';
UPDATE products SET brand = 'AUFIT', product_group = 'Điều hoà', product_type = '4.Điều hoà', capacity_value = 0.00 WHERE sku = 'AF12FHA4DI-3VN';
UPDATE products SET brand = 'AUFIT', product_group = 'Điều hoà', product_type = '4.Điều hoà', capacity_value = 0.00 WHERE sku = 'AF18FHA4DI-5VN';
UPDATE products SET brand = 'AUFIT', product_group = 'Điều hoà', product_type = '4.Điều hoà', capacity_value = 0.00 WHERE sku = 'AF24FHA4DI-3VN';
UPDATE products SET brand = '5.ELECTROLUX', product_group = NULL, product_type = '8.Khác', capacity_value = NULL WHERE sku = 'CDELEC';
UPDATE products SET brand = '5.ELECTROLUX', product_group = NULL, product_type = '8.Khác', capacity_value = NULL WHERE sku = 'CDELECPN334';
UPDATE products SET brand = 'DAIKIN', product_group = 'Điều hoà', product_type = '4.Điều hoà', capacity_value = 0.00 WHERE sku = 'DAIKDNRF25XAV1V';
UPDATE products SET brand = 'DAIKIN', product_group = 'Điều hoà', product_type = '4.Điều hoà', capacity_value = 0.00 WHERE sku = 'DAIKDNRF35XAV1V';
UPDATE products SET brand = 'DAIKIN', product_group = 'Điều hoà', product_type = '4.Điều hoà', capacity_value = 0.00 WHERE sku = 'DAIKDNRF50XV1V';
UPDATE products SET brand = 'DAIKIN', product_group = 'Điều hoà', product_type = '4.Điều hoà', capacity_value = 0.00 WHERE sku = 'DAIKDNRHF25XVMV';
UPDATE products SET brand = 'DAIKIN', product_group = 'Điều hoà', product_type = '4.Điều hoà', capacity_value = 0.00 WHERE sku = 'DAIKDNRHF35XVMV';
UPDATE products SET brand = 'DAIKIN', product_group = 'Điều hoà', product_type = '4.Điều hoà', capacity_value = 0.00 WHERE sku = 'DAIKDNRHF50VAMV';
UPDATE products SET brand = 'DAIKIN', product_group = 'Điều hoà', product_type = '4.Điều hoà', capacity_value = 0.00 WHERE sku = 'DAIKDNRKB25YVMV';
UPDATE products SET brand = 'DAIKIN', product_group = 'Điều hoà', product_type = '4.Điều hoà', capacity_value = 0.00 WHERE sku = 'DAIKDNRKB35YVMV';
UPDATE products SET brand = 'DAIKIN', product_group = 'Điều hoà', product_type = '4.Điều hoà', capacity_value = 0.00 WHERE sku = 'DAIKDNRKB35ZVMV';
UPDATE products SET brand = 'DAIKIN', product_group = 'Điều hoà', product_type = '4.Điều hoà', capacity_value = 0.00 WHERE sku = 'DAIKDNRKB50ZVMV';
UPDATE products SET brand = 'DAIKIN', product_group = 'Điều hoà', product_type = '4.Điều hoà', capacity_value = 0.00 WHERE sku = 'DAIKDNRKY50WVMV';
UPDATE products SET brand = '3.PANASONIC', product_group = NULL, product_type = '6.Gia dụng', capacity_value = NULL WHERE sku = 'PANA5SP';
UPDATE products SET brand = '3.PANASONIC', product_group = NULL, product_type = '2.Máy giặt', capacity_value = NULL WHERE sku = 'PANTOPBOARD';
UPDATE products SET brand = 'SANAKY', product_group = 'Thiết bị gia dụng', product_type = '6.Gia dụng', capacity_value = 0.00 WHERE sku = 'SANAKYSNK18N1S';
UPDATE products SET brand = '2.SHARP', product_group = 'Thiết bị gia dụng', product_type = '6.Gia dụng', capacity_value = 0.00 WHERE sku = 'SHALVSRG371VNW';
UPDATE products SET brand = '2.SHARP', product_group = 'Thiết bị gia dụng', product_type = '6.Gia dụng', capacity_value = 0.00 WHERE sku = 'SHAPSTS15PVH';
UPDATE products SET brand = '1.TOSHIBA', product_group = NULL, product_type = '8.Khác', capacity_value = NULL WHERE sku = 'TOSBP110';
UPDATE products SET brand = '1.TOSHIBA', product_group = NULL, product_type = '8.Khác', capacity_value = NULL WHERE sku = 'TOSLVSER-SGM20(S1)VN';
UPDATE products SET brand = '1.TOSHIBA', product_group = NULL, product_type = '8.Khác', capacity_value = NULL WHERE sku = 'TOST37';
UPDATE products SET brand = 'DAIKIN', product_group = 'Điều hoà', product_type = '4.Điều hoà', capacity_value = 0.00 WHERE sku = 'DAIKDNRKB25ZVMV';
