package com.elog.entity;

public enum PlanningEventType {
    TRIP_DRAFT_CREATED,
    TRIP_DRAFT_UPDATED,
    RECOMMENDATION_RUN,
    SINGLE_VEHICLE_NOT_FOUND,
    TWO_VEHICLE_FALLBACK_TRIGGERED,
    RECOMMENDATION_LIST_GENERATED,
    OPTION_SELECTED,
    OPTION_CHANGED,
    PLAN_CONFIRMED,
    DRIVER_ASSIGNED,
    DRIVER_CHANGED,
    PLAN_REPLANNED,
    PLAN_CANCELLED,
    PLAN_VERSION_CREATED,
    PLAN_VERSION_RESTORED
}
