package com.elog.entity;

public enum TripOutcomeEventType {
    TRIP_EXECUTION_CREATED,
    START_TRIP,
    ORDER_DELIVERED,
    ORDER_FAILED,
    ORDER_PARTIALLY_DELIVERED,
    STOP_STATUS_CHANGED,
    COMPLETE_TRIP,
    OUTCOME_SUBMITTED,
    OUTCOME_VALIDATED,
    OUTCOME_AMENDED,
    ADMIN_OVERRIDE_FORCE_RETURN,
    ADMIN_OVERRIDE_FORCE_COMPLETE
}
